do $$declare f jsonb:=pg_temp.schedule_fixture(31);g jsonb:=pg_temp.schedule_fixture(32);a uuid:=(f->>'agency')::uuid;b uuid:=(g->>'agency')::uuid;u uuid:=(f->>'actor')::uuid;v uuid:=(g->>'actor')::uuid;pid uuid:=(f->>'property')::uuid;d uuid:=(f->>'deal')::uuid;other jsonb;p jsonb;q jsonb;r jsonb;occ jsonb;slot jsonb;body jsonb;stamp timestamptz:=date_trunc('minute',clock_timestamp())+interval '2 days';begin
 insert into kh_private.agency_mandates(property_id,agency_id,state,reference)values(pid,b,'active',pid::text);
 perform pg_temp.kh_as(v);other:=public.kh_create_agency_deal(v,b,jsonb_build_object('propertyId',pid,'assigneeId',v,'externalContact',jsonb_build_object('name','Otro interesado privado','phone',null,'consentReference','Permiso recibido'),'clientRequestId',gen_random_uuid()));
 p:=pg_temp.visit_proposal(u,a,d,stamp);r:=pg_temp.accept_visit(u,a,p);
 perform pg_temp.kh_assert(public.kh_agency_calendar(u,a,stamp-interval '1 hour',stamp+interval '4 hours',0,30)#>>'{items,0,assigneeName}' is not null,'own_calendar_identifies_authorized_responsible');
 q:=pg_temp.visit_proposal(v,b,(other->>'id')::uuid,stamp+interval '30 minutes');
 perform pg_temp.kh_error(format('select pg_temp.accept_visit(%L,%L,%L)',v,b,q),'KH_AGENCY_VISIT_CONFLICT');
 perform pg_temp.kh_assert((select count(*) from kh_private.property_visit_slots where proposal_id in((p->>'id')::uuid,(q->>'id')::uuid))=1,'competing_agencies_cannot_confirm_overlapping_visits');
 occ:=public.kh_property_visit_occupancy(v,b,pid,stamp-interval '1 hour',stamp+interval '4 hours');
 perform pg_temp.kh_assert(jsonb_array_length(occ)=1 and (occ->0)-array['startsAt','endsAt']='{}'::jsonb,'other_agency_receives_only_busy_interval');
 perform pg_temp.kh_assert(jsonb_array_length(public.kh_agency_calendar(v,b,stamp-interval '1 hour',stamp+interval '4 hours',0,30)->'items')=0,'calendar_private_to_own_deals');
 perform public.kh_respond_agency_proposal(v,b,jsonb_build_object('proposalId',q->>'id','expectedVersion',1,'action','cancel','clientRequestId',gen_random_uuid()));
 q:=pg_temp.visit_proposal(v,b,(other->>'id')::uuid,stamp+interval '60 minutes');perform pg_temp.accept_visit(v,b,q);
 perform pg_temp.kh_assert((select count(*) from kh_private.property_visit_slots where property_id=pid)=2,'half_open_intervals_allow_adjacent_visits');
 insert into kh_private.agency_memberships(agency_id,user_id,role)values(b,u,'manager');
 perform pg_temp.kh_as(v);perform public.kh_assign_agency_deal(v,b,jsonb_build_object('dealId',g->>'deal','userId',u,'expectedVersion',1,'clientRequestId',gen_random_uuid()));
 q:=pg_temp.visit_proposal(u,b,(g->>'deal')::uuid,stamp);
 perform pg_temp.kh_error(format('select pg_temp.accept_visit(%L,%L,%L)',u,b,q),'KH_AGENCY_VISIT_CONFLICT');
 perform pg_temp.kh_assert(not exists(select 1 from kh_private.property_visit_slots where proposal_id=(q->>'id')::uuid),'same_manager_cannot_confirm_overlapping_properties');
 perform pg_temp.kh_as(u);perform pg_temp.kh_error(format('select public.kh_record_agency_visit_outcome(%L,%L,%L)',u,a,jsonb_build_object('proposalId',p->>'id','outcome','performed','expectedVersion',1,'clientRequestId',gen_random_uuid())),'KH_AGENCY_VISIT_NOT_STARTED');
 update kh_private.property_visit_slots set starts_at=clock_timestamp()-interval '2 hours',ends_at=clock_timestamp()-interval '1 hour' where proposal_id=(p->>'id')::uuid;
 perform pg_temp.kh_assert((select outcome from kh_private.property_visit_slots where proposal_id=(p->>'id')::uuid)='unrecorded','past_visit_requires_recorded_outcome');
 slot:=public.kh_record_agency_visit_outcome(u,a,jsonb_build_object('proposalId',p->>'id','outcome','performed','expectedVersion',1,'clientRequestId',gen_random_uuid()));
 perform pg_temp.kh_assert(slot->>'outcome'='performed' and (select stage from kh_private.agency_deals where id=d)='visited','performed_is_explicit');
 body:=jsonb_build_object('propertyId',pid,'expiresAt',clock_timestamp()+interval '8 days','clientRequestId',gen_random_uuid());
 perform pg_temp.kh_error(format('select public.kh_set_agency_reservation(%L,%L,%L)',u,a,body),'KH_AGENCY_INVALID_EXPIRY');
 perform pg_temp.kh_as(v);perform pg_temp.kh_error(format('select public.kh_set_agency_reservation(%L,%L,%L)',v,b,body),'KH_AGENCY_ORIGIN_REQUIRED');
 perform pg_temp.kh_as(u);r:=public.kh_set_agency_reservation(u,a,body||jsonb_build_object('expiresAt',clock_timestamp()+interval '1 day'));
 perform pg_temp.kh_assert((r->>'active')::boolean and (select availability from public.properties where id=pid)='active','reservation_requires_origin_admin_and_expiry');
 p:=pg_temp.visit_proposal(u,a,d,stamp+interval '5 hours');perform pg_temp.kh_error(format('select pg_temp.accept_visit(%L,%L,%L)',u,a,p),'KH_AGENCY_PROPERTY_RESERVED');
 perform public.kh_respond_agency_proposal(u,a,jsonb_build_object('proposalId',p->>'id','expectedVersion',1,'action','cancel','clientRequestId',gen_random_uuid()));
 update kh_private.property_reservations set expires_at=clock_timestamp()-interval '1 second' where id=(r->>'id')::uuid;
 perform pg_temp.kh_assert((select status from kh_private.agency_proposals where id=(p->>'id')::uuid)='cancelled','reservation_expiry_does_not_revive_cancelled_proposal');
 p:=pg_temp.visit_proposal(u,a,d,stamp+interval '5 hours');perform pg_temp.accept_visit(u,a,p);
 body:=jsonb_build_object('propertyId',pid,'visitDate',to_char((stamp+interval '1 day') at time zone 'America/Havana','YYYY-MM-DD'),'visitTime',to_char((stamp+interval '1 day') at time zone 'America/Havana','HH24:MI'),'durationMinutes',90,'clientRequestId',gen_random_uuid());
 perform pg_temp.kh_as(v);perform pg_temp.kh_error(format('select public.kh_create_joint_visit_slot(%L,%L,%L)',v,b,body),'KH_AGENCY_ORIGIN_REQUIRED');
 perform pg_temp.kh_as(u);slot:=public.kh_create_joint_visit_slot(u,a,body);
 p:=pg_temp.visit_proposal(u,a,d,stamp+interval '1 day',90);perform pg_temp.kh_error(format('select pg_temp.accept_visit(%L,%L,%L)',u,a,p),'KH_AGENCY_VISIT_CONFLICT');
 perform pg_temp.kh_error(format('select pg_temp.accept_visit(%L,%L,%L,%L)',u,a,p,gen_random_uuid()),'KH_AGENCY_JOINT_PERMISSION_REQUIRED');
 perform pg_temp.accept_visit(u,a,p,(slot->>'token')::uuid);
 q:=pg_temp.visit_proposal(v,b,(other->>'id')::uuid,stamp+interval '1 day',90);
 perform public.kh_join_joint_visit_slot(v,b,jsonb_build_object('proposalId',q->>'id','expectedVersion',1,'jointVisitToken',slot->>'token','externalResponse',jsonb_build_object('channel','phone','reference','Aceptación de otro interesado'),'clientRequestId',gen_random_uuid()));
 perform pg_temp.kh_assert((select count(*) from kh_private.property_visit_slots where joint_slot_id=(slot->>'id')::uuid)=2,'joint_visit_requires_explicit_origin_permission');
 occ:=public.kh_property_visit_occupancy(v,b,pid,stamp+interval '1 day',stamp+interval '2 days');
 perform pg_temp.kh_assert(jsonb_array_length(occ)=1 and not(occ->0?'token'),'joint_occupancy_does_not_disclose_token_or_buyers');
 perform pg_temp.kh_as(u);perform public.kh_withdraw_agency_mandate(u,a,jsonb_build_object('propertyId',pid,'requestingAgencyId',b,'expectedVersion',1,'clientRequestId',gen_random_uuid()));
 perform pg_temp.kh_assert((select status from kh_private.agency_proposals where id=(q->>'id')::uuid)='cancelled' and (select status from kh_private.agency_proposals where id=(p->>'id')::uuid)='accepted','collaborator_withdrawal_is_scoped');
end $$;

do $$declare pid uuid:='46000000-0000-4000-8000-000000000001';begin
 perform pg_temp.kh_assert((select count(*) from kh_private.property_visit_slots where property_id=pid and existing_conflict and ends_at=starts_at+interval '60 minutes')=2,'legacy_overlaps_import_without_rejection_and_are_flagged');
 perform pg_temp.kh_as('45000000-0000-4000-8000-000000000002');delete from public.properties where id=pid;
 perform pg_temp.kh_assert(not exists(select 1 from kh_private.agency_property_identities where property_id=pid) and not exists(select 1 from kh_private.property_visit_slots where property_id=pid),'purely_personal_deletion_purges_compatibility_occupancy_and_registry');
end $$;

do $$declare f jsonb:=pg_temp.schedule_fixture(33);a uuid:=(f->>'agency')::uuid;u uuid:=(f->>'actor')::uuid;buyer uuid:='45000000-0000-4000-8000-000000000002';manager uuid:='45000000-0000-4000-8000-000000000004';c jsonb;p jsonb;d jsonb;body jsonb;offer jsonb;completed jsonb;g jsonb;b uuid;v uuid;other jsonb;competing jsonb;stamp timestamptz;begin
 insert into kh_private.agency_memberships(agency_id,user_id,role)values(a,manager,'manager');
 perform pg_temp.kh_as(buyer);c:=public.kh_start_agency_conversation(buyer,a,jsonb_build_object('propertyId',f->>'property','clientRequestId',gen_random_uuid()));
 p:=pg_temp.visit_proposal(buyer,null,(c->>'dealId')::uuid,clock_timestamp()+interval '3 days');
 perform pg_temp.kh_as(u);body:=jsonb_build_object('proposalId',p->>'id','expectedVersion',1,'action','accept','clientRequestId',gen_random_uuid());
 perform pg_temp.kh_error(format('select public.kh_respond_agency_proposal(%L,%L,%L)',u,a,body),'KH_AGENCY_ASSIGNEE_REQUIRED');
 perform pg_temp.kh_assert((select assignee_id from kh_private.agency_deals where id=(c->>'dealId')::uuid)is null,'no_silent_admin_assignment');
 d:=public.kh_get_agency_deal(u,a,(c->>'dealId')::uuid);
 perform public.kh_assign_agency_deal(u,a,jsonb_build_object('dealId',c->>'dealId','userId',manager,'expectedVersion',d->>'version','clientRequestId',gen_random_uuid()));
 perform public.kh_respond_agency_proposal(u,a,body);
 stamp:=(p->>'visitAt')::timestamptz;
 perform pg_temp.kh_as(manager);offer:=public.kh_create_agency_proposal(manager,a,jsonb_build_object('dealId',c->>'dealId','kind','offer','amountUsd','25000','note','Propuesta del equipo','clientRequestId',gen_random_uuid()));
 completed:=pg_temp.visit_proposal(buyer,null,(c->>'dealId')::uuid,stamp+interval '1 day');
 perform pg_temp.kh_as(manager);perform public.kh_respond_agency_proposal(manager,a,jsonb_build_object('proposalId',completed->>'id','expectedVersion',1,'action','accept','clientRequestId',gen_random_uuid()));
 update kh_private.property_visit_slots set starts_at=clock_timestamp()-interval '2 hours',ends_at=clock_timestamp()-interval '1 hour' where proposal_id=(completed->>'id')::uuid;
 perform public.kh_record_agency_visit_outcome(manager,a,jsonb_build_object('proposalId',completed->>'id','outcome','performed','expectedVersion',1,'clientRequestId',gen_random_uuid()));
 perform pg_temp.kh_as(u);perform public.kh_remove_agency_member(u,a,jsonb_build_object('userId',manager,'expectedVersion',1,'clientRequestId',gen_random_uuid()));
 perform pg_temp.kh_assert((select status='accepted' and version=2 from kh_private.agency_proposals where id=(p->>'id')::uuid) and (select assignee_id is null from kh_private.agency_deals where id=(c->>'dealId')::uuid) and (select outcome='unrecorded' and assignee_id is null and version=2 from kh_private.property_visit_slots where proposal_id=(p->>'id')::uuid),'member_removal_retains_unassigned_agency_appointment');
 perform pg_temp.kh_assert((select status='pending' and created_by=manager and version=1 from kh_private.agency_proposals where id=(offer->>'id')::uuid) and (select outcome='performed' and assignee_id=manager from kh_private.property_visit_slots where proposal_id=(completed->>'id')::uuid),'member_handoff_preserves_pending_authorship_and_completed_history');
 perform pg_temp.kh_assert(public.kh_agency_calendar(u,a,stamp-interval '1 hour',stamp+interval '2 hours',0,30)#>'{items,0,assigneeId}'='null'::jsonb and public.kh_agency_calendar(u,a,stamp-interval '1 hour',stamp+interval '2 hours',0,30)#>>'{items,0,assigneeName}'='Sin asignar','current_admin_sees_unassigned_appointment');
 insert into kh_private.agency_memberships(agency_id,user_id,role)values(a,'45000000-0000-4000-8000-000000000007','coordinator');
 perform pg_temp.kh_as('45000000-0000-4000-8000-000000000007');
 perform pg_temp.kh_assert(exists(select 1 from jsonb_array_elements(public.kh_list_agency_proposals(auth.uid(),a,(c->>'dealId')::uuid,0,30)->'items') item where item->>'id'=offer->>'id' and item->>'status'='pending') and public.kh_agency_calendar(auth.uid(),a,stamp-interval '1 hour',stamp+interval '2 hours',0,30)#>'{items,0,assigneeId}'='null'::jsonb,'current_coordinator_retains_pending_history_and_unassigned_calendar_access');
 perform pg_temp.kh_as(manager);perform pg_temp.kh_error(format('select public.kh_list_agency_proposals(%L,%L,%L)',manager,a,c->>'dealId'),'KH_AGENCY_DEAL_NOT_FOUND');
 perform pg_temp.kh_error(format('select public.kh_list_agency_proposal_events(%L,%L,%L)',manager,a,p->>'id'),'KH_AGENCY_DEAL_NOT_FOUND');
 -- The former member is still eligible in another agency: his old allocation
 -- must not keep him busy, but the original property must remain occupied.
 g:=pg_temp.schedule_fixture(38);b:=(g->>'agency')::uuid;v:=(g->>'actor')::uuid;
 insert into kh_private.agency_memberships(agency_id,user_id,role)values(b,manager,'manager');
 perform public.kh_assign_agency_deal(v,b,jsonb_build_object('dealId',g->>'deal','userId',manager,'expectedVersion',1,'clientRequestId',gen_random_uuid()));
 other:=pg_temp.visit_proposal(manager,b,(g->>'deal')::uuid,stamp);perform pg_temp.accept_visit(manager,b,other);
 perform pg_temp.kh_assert((select count(*) from kh_private.property_visit_slots where assignee_id=manager and outcome='unrecorded' and starts_at=stamp)=1,'departed_manager_busy_allocation_is_released');
 insert into kh_private.agency_mandates(property_id,agency_id,reference)values((f->>'property')::uuid,b,f->>'property');
 perform pg_temp.kh_as(v);other:=public.kh_create_agency_deal(v,b,jsonb_build_object('propertyId',f->>'property','assigneeId',v,'externalContact',jsonb_build_object('name','Otro interesado','phone',null,'consentReference','Permiso expreso'),'clientRequestId',gen_random_uuid()));
 competing:=pg_temp.visit_proposal(v,b,(other->>'id')::uuid,stamp);
 perform pg_temp.kh_error(format('select pg_temp.accept_visit(%L,%L,%L)',v,b,competing),'KH_AGENCY_VISIT_CONFLICT');
 perform pg_temp.kh_as(u);perform public.kh_respond_agency_proposal(u,a,jsonb_build_object('proposalId',p->>'id','action','cancel','expectedVersion',2,'clientRequestId',gen_random_uuid()));
 perform pg_temp.accept_visit(v,b,competing);
 perform pg_temp.kh_assert((select status from kh_private.agency_proposals where id=(p->>'id')::uuid)='cancelled','later_explicit_cancellation_releases_retained_property_occupancy');
end $$;

do $$declare f jsonb:=pg_temp.schedule_fixture(39);a uuid:=(f->>'agency')::uuid;u uuid:=(f->>'actor')::uuid;manager uuid:='45000000-0000-4000-8000-000000000005';d jsonb;p jsonb;begin
 insert into kh_private.agency_memberships(agency_id,user_id,role)values(a,manager,'manager');
 d:=public.kh_assign_agency_deal(u,a,jsonb_build_object('dealId',f->>'deal','userId',manager,'expectedVersion',1,'clientRequestId',gen_random_uuid()));
 p:=pg_temp.visit_proposal(manager,a,(d->>'id')::uuid,clock_timestamp()+interval '6 days');perform pg_temp.accept_visit(manager,a,p);
 update kh_private.agency_settings set enabled=false;
 delete from auth.users where id=manager;
 perform pg_temp.kh_assert((select status='accepted' from kh_private.agency_proposals where id=(p->>'id')::uuid) and (select outcome='unrecorded' and assignee_id is null from kh_private.property_visit_slots where proposal_id=(p->>'id')::uuid) and (select assignee_id is null from kh_private.agency_deals where id=(d->>'id')::uuid),'direct_auth_deletion_with_module_off_hands_off_appointment');
 update kh_private.agency_settings set enabled=true;
end $$;
do $$declare f jsonb:=pg_temp.schedule_fixture(34);a uuid:=(f->>'agency')::uuid;u uuid:=(f->>'actor')::uuid;pid uuid:='46000000-0000-4000-8000-000000000002';seller uuid:='45000000-0000-4000-8000-000000000002';buyer uuid:='45000000-0000-4000-8000-000000000006';conv uuid:='46000000-0000-4000-8000-000000000006';d jsonb;p jsonb;n jsonb;body jsonb;r jsonb;stamp timestamptz:=date_trunc('minute',clock_timestamp())+interval '4 days';begin
 insert into kh_private.agency_mandates(property_id,agency_id,reference)values(pid,a,pid::text);
 perform pg_temp.kh_as(u);d:=public.kh_create_agency_deal(u,a,jsonb_build_object('propertyId',pid,'assigneeId',u,'externalContact',jsonb_build_object('name','Visita de agencia','phone',null,'consentReference','Permiso comprobado'),'clientRequestId',gen_random_uuid()));
 p:=pg_temp.visit_proposal(u,a,(d->>'id')::uuid,stamp);p:=pg_temp.accept_visit(u,a,p);
 perform pg_temp.kh_as(buyer);n:=public.kh_create_negotiation(buyer,jsonb_build_object('conversationId',conv,'kind','visit','visitDate',to_char(stamp at time zone 'America/Havana','YYYY-MM-DD'),'visitTime',to_char(stamp at time zone 'America/Havana','HH24:MI'),'note','Visita personal','clientRequestId',gen_random_uuid()));
 body:=jsonb_build_object('id',n->>'id','action','accept','expectedVersion',1,'clientRequestId',gen_random_uuid());
 perform pg_temp.kh_as(seller);perform pg_temp.kh_error(format('select public.kh_respond_negotiation(%L,%L)',seller,body),'KH_AGENCY_VISIT_CONFLICT');
 perform pg_temp.kh_assert((select status from public.kh_negotiations where id=(n->>'id')::uuid)='pending','personal_conflict_rolls_back_status_receipt_and_chat');
 perform pg_temp.kh_as(u);perform public.kh_respond_agency_proposal(u,a,jsonb_build_object('proposalId',p->>'id','action','cancel','expectedVersion',2,'clientRequestId',gen_random_uuid()));
 perform pg_temp.kh_as(seller);r:=public.kh_respond_negotiation(seller,body);
 perform pg_temp.kh_assert(public.kh_respond_negotiation(seller,body)=r and (select count(*) from kh_private.property_visit_slots where personal_negotiation_id=(n->>'id')::uuid)=1,'personal_acceptance_receipt_and_sixty_minute_occupancy');
 perform pg_temp.kh_error(format('select public.kh_respond_negotiation(%L,%L)',seller,body||'{"action":"decline"}'::jsonb),'KH_NEG_REQUEST_CONFLICT');
 perform pg_temp.kh_as(buyer);update auth.users set email_confirmed_at=null where id=buyer;
 perform public.kh_respond_negotiation(buyer,jsonb_build_object('id',n->>'id','action','cancel','expectedVersion',2,'clientRequestId',gen_random_uuid()));
 perform pg_temp.kh_assert((select outcome from kh_private.property_visit_slots where personal_negotiation_id=(n->>'id')::uuid)='cancelled','personal_historical_participant_cancellation_preserves_existing_account_rules');
 update auth.users set email_confirmed_at=now() where id=buyer;
 p:=pg_temp.visit_proposal(u,a,(d->>'id')::uuid,stamp);perform pg_temp.accept_visit(u,a,p);
 perform pg_temp.kh_as(seller);delete from public.properties where id=pid;
 perform pg_temp.kh_assert((select closed_reason from kh_private.agency_proposals where id=(p->>'id')::uuid)='personal_source_deleted' and exists(select 1 from kh_private.agency_property_identities where property_id=pid),'personal_source_deletion_keeps_private_history_without_sale');
end $$;
do $$declare f jsonb:=pg_temp.schedule_fixture(35);g jsonb:=pg_temp.schedule_fixture(36);a uuid:=(f->>'agency')::uuid;b uuid:=(g->>'agency')::uuid;u uuid:=(f->>'actor')::uuid;v uuid:=(g->>'actor')::uuid;owner uuid:='45000000-0000-4000-8000-000000000001';manager uuid:='45000000-0000-4000-8000-000000000004';pid uuid:=(f->>'property')::uuid;d jsonb;p jsonb;q jsonb;r jsonb;body jsonb;begin
 insert into kh_private.agency_memberships(agency_id,user_id,role)values(a,manager,'manager');
 insert into kh_private.agency_mandates(property_id,agency_id,reference)values(pid,b,pid::text);
 perform pg_temp.kh_as(v);d:=public.kh_create_agency_deal(v,b,jsonb_build_object('propertyId',pid,'assigneeId',v,'externalContact',jsonb_build_object('name','Otro cliente','phone',null,'consentReference','Permiso expreso'),'clientRequestId',gen_random_uuid()));
 p:=pg_temp.visit_proposal(u,a,(f->>'deal')::uuid,clock_timestamp()+interval '5 days');perform pg_temp.accept_visit(u,a,p);
 q:=pg_temp.visit_proposal(v,b,(d->>'id')::uuid,clock_timestamp()+interval '6 days');perform pg_temp.accept_visit(v,b,q);
 perform pg_temp.kh_as(u);body:=jsonb_build_object('propertyId',pid,'expiresAt',clock_timestamp()+interval '1 day','clientRequestId',gen_random_uuid());r:=public.kh_set_agency_reservation(u,a,body);
 perform pg_temp.kh_assert(public.kh_get_agency_reservation(u,a,pid)->>'id'=r->>'id','origin_can_reload_reservation_for_explicit_release');
 perform pg_temp.kh_as(manager);perform pg_temp.kh_error(format('select public.kh_set_agency_reservation(%L,%L,%L)',manager,a,body),'KH_AGENCY_ROLE_REQUIRED');
 perform pg_temp.kh_error(format('select public.kh_list_agency_proposals(%L,%L,%L)',manager,a,f->>'deal'),'KH_AGENCY_DEAL_NOT_FOUND');
 perform pg_temp.kh_error(format('select public.kh_list_agency_proposal_events(%L,%L,%L)',manager,a,p->>'id'),'KH_AGENCY_DEAL_NOT_FOUND');
 perform pg_temp.kh_as(v);perform pg_temp.kh_error(format('select public.kh_list_agency_proposal_events(%L,%L,%L)',v,b,p->>'id'),'KH_AGENCY_DEAL_NOT_FOUND');
 perform pg_temp.kh_as(owner);perform public.kh_review_agency(owner,jsonb_build_object('agencyId',a,'decision','suspend','expectedVersion',(select version from kh_private.agencies where id=a),'note','Suspensión de origen','clientRequestId',gen_random_uuid()));
 perform pg_temp.kh_assert((select count(*) from kh_private.agency_proposals where id in((p->>'id')::uuid,(q->>'id')::uuid) and status='cancelled' and closed_reason='origin_agency_suspended')=2 and (select released_at is not null from kh_private.property_reservations where id=(r->>'id')::uuid),'origin_suspension_ends_all_agencies_future_slots_and_reservation');
 perform pg_temp.kh_assert((select availability from public.properties where id=pid)='paused','origin_suspension_is_not_sale');
end $$;
do $$declare f jsonb:=pg_temp.schedule_fixture(37);a uuid:=(f->>'agency')::uuid;u uuid:=(f->>'actor')::uuid;owner uuid:='45000000-0000-4000-8000-000000000001';buyer uuid:='45000000-0000-4000-8000-000000000002';p jsonb;conv uuid:=gen_random_uuid();body jsonb;begin
 p:=pg_temp.visit_proposal(u,a,(f->>'deal')::uuid,clock_timestamp()+interval '3 days');perform pg_temp.accept_visit(u,a,p);
 update kh_private.property_visit_slots set starts_at=clock_timestamp()-interval '2 hours',ends_at=clock_timestamp()-interval '1 hour' where proposal_id=(p->>'id')::uuid;
 perform public.kh_record_agency_visit_outcome(u,a,jsonb_build_object('proposalId',p->>'id','outcome','no_show','expectedVersion',1,'clientRequestId',gen_random_uuid()));
 perform kh_private.terminate_mandate_flows((f->>'property')::uuid,a,'authorization_withdrawn');
 perform pg_temp.kh_assert((select outcome from kh_private.property_visit_slots where proposal_id=(p->>'id')::uuid)='no_show' and (select status from kh_private.agency_proposals where id=(p->>'id')::uuid)='accepted','absence_is_explicit_and_preserved_as_historical_fact');
 insert into public.kh_conversations(id,property_id,property_title,property_location,buyer_id,seller_id)values(conv,(f->>'property')::uuid,'Custodia técnica','Vedado',buyer,owner);
 perform pg_temp.kh_as(buyer);body:=jsonb_build_object('conversationId',conv,'kind','offer','amountUsd','25000','note','','clientRequestId',gen_random_uuid());
 perform pg_temp.kh_error(format('select public.kh_create_negotiation(%L,%L)',buyer,body),'KH_AGENCY_CONTEXT_REQUIRED');
 -- Seed a pre-migration receipt through the preserved legacy implementation.
 p:=kh_private.kh_create_negotiation_pre_scheduling(buyer,body);
 perform pg_temp.kh_assert(public.kh_create_negotiation(buyer,body)=p,'corporate_historical_personal_create_receipt_remains_readable');
 perform pg_temp.kh_as(owner);body:=jsonb_build_object('id',p->>'id','action','accept','expectedVersion',1,'clientRequestId',gen_random_uuid());p:=kh_private.kh_respond_negotiation_pre_scheduling(owner,body);
 perform pg_temp.kh_assert(public.kh_respond_negotiation(owner,body)=p,'corporate_historical_personal_response_receipt_does_not_authorize_a_new_write');
 perform pg_temp.kh_assert(not has_function_privilege('authenticated','kh_private.agency_common_flow_mutex(uuid,uuid,uuid,uuid[])','execute') and not has_function_privilege('authenticated','kh_private.kh_respond_negotiation_pre_scheduling(uuid,jsonb)','execute') and not has_table_privilege('authenticated','kh_private.agency_proposal_events','select'),'private_bypass_and_history_tables_not_executable_or_readable');
end $$;
