import test from 'node:test';
import assert from 'node:assert/strict';
import {createAgencyClosureRepository} from '../src/agencies/closures/repository.ts';
const id=(n:number)=>`45000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const context={userId:id(1),agencyId:id(2),generation:1,accessToken:'pinned',signal:new AbortController().signal,checkpoint(){}};
const request={id:id(3),propertyId:id(4),cycleId:id(5),originAgencyId:id(6),executingAgencyId:id(2),executingManagerId:id(1),winningDealId:id(7),amountUsd:30000,occurredAt:'2026-10-01T12:00:00Z',state:'pending',version:1,propertyTitle:'Casa',executingAgencyName:'Agencia',executingManagerName:'Gestor',buyerLabel:'Contacto',evidenceSummary:'Sin oferta aceptada',expectedPropertyVersion:2,expectedAuthorityVersion:1,affectedVisits:1,affectedDeals:2,canDecide:false,canCancel:true,closure:null};
const input={winningDealId:id(7),executingManagerId:id(1),amountUsd:30000,occurredAt:request.occurredAt,expectedPropertyVersion:2,expectedAuthorityVersion:1,clientRequestId:id(9)};
function fixture(data:unknown){const calls:any[]=[];const client={rpc(name:string,args:any){calls.push({name,args});return{setHeader(_k:string,v:string){assert.equal(v,'Bearer pinned');return this},async abortSignal(){return{data,error:null}}}}};return{repo:createAgencyClosureRepository(client as any),calls};}
test('request pins agency and actor without inferring execution or origin',async()=>{const{repo,calls}=fixture({...request,privateContact:'not projected'});const r=await repo.request(input,context);assert.equal(r.executingManagerId,id(1));assert.equal('privateContact'in r,false);assert.equal(calls[0].args.p_actor_id,id(1));assert.equal(calls[0].args.p_agency_id,id(2));assert.equal('originAgencyId'in calls[0].args.p_payload,false);});
test('personal authority uses account context and bounded personal endpoint',async()=>{const{repo,calls}=fixture({items:[request],hasMore:false});await repo.personalList(30,context);assert.equal(calls[0].name,'kh_list_personal_sale_requests');assert.equal('p_agency_id'in calls[0].args,false);assert.equal(calls[0].args.p_offset,30);});
test('invalid executor money versions date and forged origin never reach RPC',async()=>{const{repo,calls}=fixture(request);for(const bad of[{amountUsd:0},{amountUsd:NaN},{amountUsd:1.001},{executingManagerId:null},{expectedAuthorityVersion:0},{occurredAt:'tomorrow'},{originAgencyId:id(8)}])await assert.rejects(repo.request({...input,...bad},context));assert.equal(calls.length,0);});
test('decision rejects foreign request receipt and cross-context stale response',async()=>{const{repo}=fixture({request,closure:null});await assert.rejects(repo.decide({requestId:id(8),action:'reject',expectedRequestVersion:1,expectedPropertyVersion:2,expectedAuthorityVersion:1,note:'Revisar',clientRequestId:id(9)},context));let changed=false;const c={...context,checkpoint(){if(changed)throw Error('KH_ACCOUNT_CHANGED')}};const client={rpc(){return{setHeader(){return this},async abortSignal(){changed=true;return{data:{items:[],hasMore:false},error:null}}}}};await assert.rejects(createAgencyClosureRepository(client as any).list({scope:'incoming',offset:0},c),/KH_ACCOUNT_CHANGED/);});
test('closure preparation returns canonical versions while preserving own historical deal identity',async()=>{const{repo,calls}=fixture({dealId:id(7),propertyId:id(4),propertyTitle:'Casa común',expectedPropertyVersion:4,expectedAuthorityVersion:2,executingManagerId:id(1),executingManagerName:'Responsable actual'});const p=await repo.prepare(id(7),context);assert.equal(p.propertyId,id(4));assert.equal(p.executingManagerId,id(1));assert.equal(calls[0].args.p_deal_id,id(7));});
