import test from 'node:test';
import assert from 'node:assert/strict';
import {createAgencyController} from '../src/agencies/controller.ts';
import type {AgencyRepository} from '../src/agencies/repository.ts';
import * as screens from '../src/agencies/screenRequests.ts';
const actor='45000000-0000-4000-8000-000000000002',agency='45000000-0000-4000-8001-000000000001';
const summary={id:agency,tradeName:'Casas',state:'approved',version:2,verified:false,verificationVersion:1,logoPath:null};
const context={userId:actor,accessToken:'captured',signal:new AbortController().signal,checkpoint(){},release(){}};
function deferred(){let resolve!:(value:string)=>void;return {promise:new Promise<string>(r=>{resolve=r}),resolve};}
test('reversed owner view responses cannot replace the latest data, error or loading',async()=>{assert.ok(screens);const scope=screens.createAgencyScreenRequestScope();scope.enter('pending:0');const old=scope.begin(),late=deferred();let view='',loading=true;const first=late.promise.then(value=>{old.checkpoint(context);view=value;}).catch(()=>{if(old.current())view='old error';}).finally(()=>{if(old.current())loading=false;});scope.enter('rejected:30');const current=scope.begin();current.checkpoint(context);view='new page';late.resolve('private old page');await first;assert.equal(view,'new page');assert.equal(loading,true);scope.leave();assert.throws(()=>current.checkpoint(context),/CONTEXT_CHANGED/);});
function fixture(){let role='admin',version=1,removed=false;const repository={capabilities:async()=>({enabled:true}),listMine:async()=>removed?[]:[summary],membership:async()=>removed?null:{agencyId:agency,userId:actor,role,state:'active',version},listInvitations:async()=>({items:[],hasMore:false}),listMembers:async()=>({items:[{agencyId:agency,userId:actor,role,state:'active',version}],hasMore:false})} as unknown as AgencyRepository;const controller=createAgencyController(repository);controller.setSession({userId:actor,accessToken:'captured'});return {controller,repository,remove:()=>{removed=true},reduce:()=>{role='manager';version++},renew:()=>{version++}};}
test('foreground team refresh clears members after membership removal',async()=>{assert.ok(screens);const f=fixture();await f.controller.refreshAgencies();await f.controller.setActiveAgency(agency);f.remove();const result=await screens.loadAgencyTeamPage({...f.controller,getCurrentWorkspace:f.controller.getSnapshot,repository:f.repository},false,null,()=>{});assert.deepEqual(result.members,[]);assert.equal(result.agencyId,null);assert.equal(f.controller.getSnapshot().membership,null);});
test('foreground team refresh adopts reduced role without losing selected agency',async()=>{assert.ok(screens);const f=fixture();await f.controller.refreshAgencies();await f.controller.setActiveAgency(agency);const old=f.controller.getSnapshot().generation;f.reduce();const result=await screens.loadAgencyTeamPage({...f.controller,getCurrentWorkspace:f.controller.getSnapshot,repository:f.repository},false,null,()=>{});assert.equal(result.members[0].role,'manager');assert.ok(result.generation>old);assert.equal(result.agencyId,agency);assert.equal(f.controller.getSnapshot().membership?.role,'manager');});
test('unavailable or suspended team session returns a caught failure and no leaked context',async()=>{assert.ok(screens);const f=fixture();f.controller.setSession(null);await assert.rejects(screens.loadAgencyTeamPage({...f.controller,getCurrentWorkspace:f.controller.getSnapshot,repository:f.repository},false,null,()=>{}),/SESSION_REQUIRED/);});
test('private verification state changes key on membership generation change',()=>{assert.ok(screens);assert.notEqual(screens.agencyPrivateScreenKey(actor,agency,1),screens.agencyPrivateScreenKey(actor,agency,2));});

test('same admin membership version renewal invalidates a private verification response and draft key',async()=>{const f=fixture();await f.controller.refreshAgencies();await f.controller.setActiveAgency(agency);const first=f.controller.captureAgencyContext(),oldKey=screens.agencyPrivateScreenKey(actor,agency,first.generation);const scope=screens.createAgencyScreenRequestScope();scope.enter(oldKey);const ticket=scope.begin();f.renew();await f.controller.refreshAgencies();const state=f.controller.getSnapshot(),currentKey=screens.agencyPrivateScreenKey(actor,state.activeAgencyId,state.generation);scope.enter(currentKey);assert.throws(()=>ticket.checkpoint(first),/CONTEXT_CHANGED/);assert.notEqual(oldKey,currentKey);assert.equal(state.membership?.role,'admin');assert.equal(state.activeAgencyId,agency);first.release();});
