create function pg_temp.kh_assert(ok boolean,label text) returns void language plpgsql as $$ begin if ok is not true then raise exception 'KH TEST: %',label;end if;end $$;
create function pg_temp.kh_error(statement text,expected text) returns void language plpgsql as $$ begin begin execute statement;exception when others then if strpos(sqlerrm,expected)>0 then return;end if;raise exception 'Wrong error %, expected %',sqlerrm,expected;end;raise exception 'KH TEST: missing error %',expected;end $$;
create function pg_temp.kh_as(actor uuid) returns void language plpgsql as $$ begin perform set_config('request.jwt.claim.sub',coalesce(actor::text,''),true);perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated','session_id',md5(actor::text||':session')::uuid)::text,true);end $$;
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) select ('43000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'assisted-'||n||'@example.invalid',now(),jsonb_build_object('display_name','Fixture '||n) from generate_series(1,5) n;
insert into auth.sessions(id,user_id,not_after) select md5(id::text||':session')::uuid,id,now()+interval '1 day' from auth.users where id::text like '43000000-%';
insert into kh_private.platform_owner(singleton,user_id) values(true,'43000000-0000-4000-8000-000000000001') on conflict(singleton) do update set user_id=excluded.user_id;
update kh_private.assisted_listing_settings set official_publisher_id='43000000-0000-4000-8000-000000000001',transfers_enabled=true;
insert into public.kh_admins(user_id) values('43000000-0000-4000-8000-000000000003');
create function pg_temp.kh_collaborator(target uuid default '43000000-0000-4000-8000-000000000002') returns uuid language plpgsql as $$ declare j jsonb;begin
 j:=public.kh_admin_save_assisted_collaborator(auth.uid(),jsonb_build_object('clientRequestId',gen_random_uuid(),'kind','agency','privateName','Agencia fixture','privateContact','solo fixture privado','contactChannel','manual','accountId',target,'linkEvidenceReference','confirmación sintética'));
 return (j->>'id')::uuid;end $$;
create function pg_temp.kh_offer(c uuid,ids uuid[]) returns jsonb language plpgsql as $$ begin
 return public.kh_offer_listing_transfer(auth.uid(),jsonb_build_object('clientRequestId',gen_random_uuid(),'collaboratorId',c,'expectedCollaboratorVersion',(select version from kh_private.assisted_collaborators where id=c),'recipientId',(select account_id from kh_private.assisted_collaborators where id=c),'items',(select jsonb_agg(jsonb_build_object('propertyId',p.id,'expectedVersion',p.version,'expectedProvenanceVersion',r.version) order by p.id) from public.properties p join kh_private.assisted_listing_records r on r.property_id=p.id where p.id=any(ids))));
end $$;
create function pg_temp.kh_listing(c uuid,r text) returns uuid language plpgsql as $$ declare j jsonb; path text:='43000000-0000-4000-8000-000000000001/'||r||'/photo.jpg';begin
 insert into storage.objects(bucket_id,name,owner_id) values('property-photos',path,'43000000-0000-4000-8000-000000000001');
 j:=public.kh_save_assisted_property(auth.uid(),jsonb_build_object('ownerId',auth.uid(),'clientRequestId',r,'title','Casa fixture','location','Vedado','province','La Habana','type','Casa','description','Una vivienda sintética de prueba, sin datos reales.','price',50000,'area',50,'bedrooms',2,'bathrooms',1,'amenities','[]'::jsonb,'photoPaths',jsonb_build_array(path),'moderation','pending','operation','sale'),jsonb_build_object('collaboratorId',c,'collaboratorReference',r,'sourceChannel','direct','receivedAt',now()-interval '1 minute','consentText','Permiso sintético de publicación de texto y fotos.','consentVersion','v1','consentAt',now()-interval '1 minute','evidenceReference','fixture privada','lastConfirmedAt',now()-interval '1 minute'));
 return (j->>'id')::uuid;end $$;
