import {randomUUID} from 'expo-crypto';
import {useFocusEffect,useLocalSearchParams} from 'expo-router';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Image,Modal,ScrollView,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useAuth} from '../auth/AuthProvider';
import {useAgencyWorkspace} from '../agencies/useAgencyWorkspace';
import type {CapturedAccountContext} from '../agencies/controller';
import {createAgencyScreenRequestScope} from '../agencies/screenRequests';
import {agencyError} from '../agencies/domain';
import {createAgencyAssetsRepository} from '../agencies/assets';
import {createDeadlineFetch} from '../lib/fetchTimeout';
import {loadAgencyReviewDetail} from '../agencies/review';
import {agencyStateLabel,agencyVerificationPresentation,canReviewAgency} from '../agencies/registration';
import type {AgencyApplication,AgencyState,AgencyVerificationRequest,AgencyVerificationRequestState} from '../agencies/types';
import {supabase} from '../lib/supabase';
import {AgencyTextField,useAgencyFormStyles} from '../components/agencies/AgencyRegistrationFields';
import {AgencyVerifiedBadge} from '../components/agencies/AgencyVerifiedBadge';
import {Button,EmptyState,Notice,PageTitle,Pill} from '../components/ui';
type Detail={application:AgencyApplication;request:AgencyVerificationRequest|null;logoUrl?:string|null};
type Choice={actorId:string;detail:Detail;kind:'recovery';decision:'recover';requestId?:undefined}|{actorId:string;requestId?:string;detail:Detail;kind:'application';decision:'approve'|'needs_changes'|'reject'|'suspend'}|{actorId:string;requestId?:string;detail:Detail;kind:'verification';decision:'grant'|'needs_changes'|'reject'|'revoke'};
const actionLabels={recover:'Recuperar inmobiliaria',approve:'Aprobar inmobiliaria',needs_changes:'Pedir correcciones',reject:'Rechazar',suspend:'Suspender inmobiliaria',grant:'Conceder verificación',revoke:'Retirar verificación'};
export default function AgencyReviewsScreen(){
 const params=useLocalSearchParams<{section?:string}>();
 const auth=useAuth(),workspace=useAgencyWorkspace(),{colors,styles:s}=useAgencyFormStyles();
 const owner=canReviewAgency(auth)&&!auth.suspended&&Boolean(auth.session),[section,setSection]=useState<'application'|'verification'>(params.section==='verification'?'verification':'application'),[agencyState,setAgencyState]=useState<AgencyState>('pending'),[verificationState,setVerificationState]=useState<AgencyVerificationRequestState|'all'>('pending'),[offset,setOffset]=useState(0),[page,setPage]=useState<{actorId:string;items:Detail[];hasMore:boolean}|null>(null),[selection,setSelection]=useState<Choice|null>(null),[newAdminId,setNewAdminId]=useState(''),[note,setNote]=useState(''),[issue,setIssue]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 useEffect(()=>{setSection(params.section==='verification'?'verification':'application');setOffset(0)},[params.section]);
 const viewKey=`${auth.user?.id??''}:${section}:${agencyState}:${verificationState}:${offset}`,scope=useRef(createAgencyScreenRequestScope()).current;
 const items=page&&page.actorId===auth.user?.id&&owner?page.items:[],selected=selection?.actorId===auth.user?.id&&owner?selection:null;
 const load=useCallback(async()=>{
 if(!owner||!auth.user||auth.suspended||!auth.session||!workspace.repository||!supabase)return;
 const ticket=scope.begin();let context:CapturedAccountContext|null=null;setLoading(true);setIssue('');
 try{context=workspace.captureAccountContext();let result:{items:Detail[];hasMore:boolean};
 if(section==='application'||verificationState==='all'){
 const list=await workspace.repository.listReviews(section==='application'?agencyState:'approved',offset,context);result={items:list.items.map(application=>({application,request:null})),hasMore:list.hasMore};
 }else{
 const list=await workspace.repository.listVerificationReviews(verificationState,offset,context);
 const detail=await Promise.all(list.items.map(request=>loadAgencyReviewDetail(supabase!,request.agencyId,context!,request.id)));result={items:detail,hasMore:list.hasMore};
 }
 ticket.checkpoint(context);setPage({actorId:context.userId,...result});
 }catch(cause){try{ticket.checkpoint(context??undefined);setPage(null);setIssue(agencyError(cause));}catch{}}
 finally{try{ticket.checkpoint(context??undefined);setLoading(false);}catch{}context?.release();}
 },[owner,auth.user?.id,auth.suspended,auth.session,workspace.repository,workspace.captureAccountContext,section,agencyState,verificationState,offset]);
 useFocusEffect(useCallback(()=>{scope.enter(viewKey);setPage(null);setSelection(null);setNote('');setNewAdminId('');setIssue('');setBusy(false);setLoading(false);void load();return()=>scope.leave();},[load,viewKey,scope]));
 async function choose(detail:Detail,kind:Choice['kind'],decision:Choice['decision']){
 if(!owner||!auth.user||auth.suspended||!auth.session||!supabase||busy||loading)return;
 const ticket=scope.begin();let context:CapturedAccountContext|null=null;setBusy(true);setIssue('');
 try{context=workspace.captureAccountContext();const current:Detail=await loadAgencyReviewDetail(supabase,detail.application.agency.id,context,kind==='verification'?detail.request?.id:undefined);if(current.application.agency.logoPath){current.logoUrl=await createAgencyAssetsRepository(process.env.EXPO_PUBLIC_SUPABASE_URL?.trim()??'',process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY?.trim()??'',createDeadlineFetch()).sign(current.application.agency.logoPath,context);}ticket.checkpoint(context);setNote('');setNewAdminId('');setSelection({actorId:context.userId,requestId:kind==='verification'?detail.request?.id:undefined,detail:current,kind,decision} as Choice);}
 catch(cause){try{ticket.checkpoint(context??undefined);setIssue(agencyError(cause));}catch{}}
 finally{try{ticket.checkpoint(context??undefined);setBusy(false);}catch{}context?.release();}
 }
 async function confirm(){
 if(!selected||!workspace.repository||!supabase||auth.suspended||!auth.session||busy)return;if(note.trim().length<(selected.kind==='recovery'?10:3)){setIssue('Escribe el motivo; para recuperar una agencia, incluye cómo comprobaste la identidad del responsable.');return;}
 const ticket=scope.begin();let context:CapturedAccountContext|null=null;setBusy(true);setIssue('');
 try{context=workspace.captureAccountContext();const a=selected.detail.application.agency,r=selected.detail.request;
 if(selected.kind==='verification'){const latest=await loadAgencyReviewDetail(supabase,a.id,context,selected.requestId);ticket.checkpoint(context);if(selected.requestId&&r&&(latest.request?.id!==r.id||latest.request.version!==r.version||!['pending','needs_changes'].includes(latest.request.state)))throw Error('KH_AGENCY_VERSION_CONFLICT');}
 if(selected.kind==='recovery')await workspace.repository.recoverAgency({agencyId:a.id,newAdminId:newAdminId.trim(),reason:note.trim(),expectedVersion:a.version,clientRequestId:randomUUID()},context);
 else if(selected.kind==='application')await workspace.repository.reviewAgency({agencyId:a.id,decision:selected.decision,note:note.trim(),expectedVersion:a.version,clientRequestId:randomUUID()},context);
 else{const usesRequest=selected.decision!=='revoke'&&r&&['pending','needs_changes'].includes(r.state);await workspace.repository.reviewVerification({agencyId:a.id,decision:selected.decision,note:note.trim(),expectedAgencyVersion:a.version,expectedVerificationVersion:a.verificationVersion,...(usesRequest?{requestId:r.id,expectedRequestVersion:r.version}:{}),clientRequestId:randomUUID()},context);}
 ticket.checkpoint(context);setSelection(null);setNote('');setBusy(false);await load();await workspace.refreshAgencies();
 }catch(cause){try{ticket.checkpoint(context??undefined);setIssue(agencyError(cause));}catch{}}
 finally{try{ticket.checkpoint(context??undefined);setBusy(false);}catch{}context?.release();}
 }
 function changeSection(value:'application'|'verification'){if(busy||value===section)return;scope.invalidate();setPage(null);setOffset(0);setSection(value);}
 return <SafeAreaView style={s.safe} edges={['top','bottom','left','right']}><ScrollView contentContainerStyle={s.content}><PageTitle title="Revisión de inmobiliarias" subtitle="Aprobación inicial y verificación son decisiones independientes." back fallback="/administration"/>
 {!owner?<EmptyState icon="lock-closed-outline" title="Acceso reservado" description="Solo el propietario de KarmaHouse puede aprobar agencias y conceder o retirar su verificación."/>:<>
 <View style={s.wrap}><Pill label="Aprobación inicial" active={section==='application'} onPress={()=>changeSection('application')}/><Pill label="Verificación" active={section==='verification'} onPress={()=>changeSection('verification')}/></View>
 <View style={s.wrap}>{section==='application'?(['pending','needs_changes','rejected','approved','suspended'] as const).map(state=><Pill key={state} label={agencyStateLabel[state]} active={agencyState===state} onPress={()=>{if(!busy&&state!==agencyState){scope.invalidate();setPage(null);setOffset(0);setAgencyState(state);}}}/>):(['pending','needs_changes','rejected','all'] as const).map(state=><Pill key={state} label={state==='all'?'Agencias aprobadas':agencyVerificationPresentation(false,state).label} active={verificationState===state} onPress={()=>{if(!busy&&state!==verificationState){scope.invalidate();setPage(null);setOffset(0);setVerificationState(state);}}}/>)}</View>
 <Button label="Actualizar revisiones" secondary onPress={()=>void load()} loading={loading} disabled={busy}/>{issue&&!selected&&<Notice error>{issue}</Notice>}{loading&&<ActivityIndicator color={colors.primary}/>} {!loading&&!items.length&&<EmptyState title="Sin solicitudes en esta vista" description="Actualiza o elige otro estado para consultar las revisiones."/>}
 {items.map(detail=>{const a=detail.application.agency,r=detail.request;return <View key={r?.id??a.id} style={s.card}><View style={s.row}><Text style={s.title}>{a.tradeName}</Text><AgencyVerifiedBadge verified={a.verified} agencyName={a.tradeName}/></View><Text style={s.copy}>{agencyStateLabel[a.state]}</Text><Text style={s.copy}>Responsable privado: {detail.application.input.responsibleFullName}</Text><Text style={s.copy}>Correo {detail.application.emailConfirmed?'confirmado':'pendiente de confirmación'}</Text><Text style={s.copy}>{detail.application.input.description}</Text><Text style={s.copy}>{detail.application.input.businessPhone} · {detail.application.input.province}, {detail.application.input.municipality}</Text><Text style={s.copy}>Zonas: {detail.application.input.serviceAreas.join(', ')}</Text><Text style={s.copy}>Oficina: {detail.application.input.officeAddress??'No indicada'} · {detail.application.input.publishOfficeAddress?'Publicar dirección':'Dirección privada'}</Text>{a.logoPath&&<Notice>Logo privado guardado para revisión.</Notice>}{detail.application.input.evidenceReferences.map((reference,index)=><Text key={index} selectable style={s.copy}>Referencia privada: {reference}</Text>)}{detail.application.reviewNote&&<Notice>{detail.application.reviewNote}</Notice>}
 {section==='application'?<View style={s.form}>{['pending','needs_changes','rejected'].includes(a.state)&&<Button label="Aprobar inmobiliaria" disabled={busy||loading||!detail.application.emailConfirmed} onPress={()=>void choose(detail,'application','approve')}/>} {['pending','needs_changes','rejected'].includes(a.state)&&<><Button secondary label="Pedir correcciones" disabled={busy||loading} onPress={()=>void choose(detail,'application','needs_changes')}/><Button secondary label="Rechazar solicitud" disabled={busy||loading} onPress={()=>void choose(detail,'application','reject')}/></>}{a.state==='suspended'&&<Button label="Recuperar inmobiliaria" disabled={busy||loading} onPress={()=>void choose(detail,'recovery','recover')}/>} {a.state==='approved'&&<Button secondary label="Suspender inmobiliaria" disabled={busy||loading} onPress={()=>void choose(detail,'application','suspend')}/>}</View>:<View style={s.form}>{r&&<><Text style={s.title}>{agencyVerificationPresentation(a.verified,r.state).label}</Text><Text style={s.copy}>{r.input.message}</Text>{r.input.evidenceReferences.map((reference,index)=><Text key={index} selectable style={s.copy}>Evidencia privada: {reference}</Text>)}{r.reviewNote&&<Notice>{r.reviewNote}</Notice>}</>}{a.state==='approved'&&(!r||['pending','needs_changes'].includes(r.state))&&<Button label={a.verified?'Retirar verificación':'Conceder verificación'} secondary={a.verified} disabled={busy||loading} onPress={()=>void choose(detail,'verification',a.verified?'revoke':'grant')}/>} {r&&['pending','needs_changes'].includes(r.state)&&<><Button secondary label="Pedir correcciones de verificación" disabled={busy||loading} onPress={()=>void choose(detail,'verification','needs_changes')}/><Button secondary label="Rechazar verificación" disabled={busy||loading} onPress={()=>void choose(detail,'verification','reject')}/></>}</View>}
 </View>})}
 <View style={s.row}><Button secondary label="Anterior" disabled={busy||loading||offset===0} onPress={()=>{scope.invalidate();setPage(null);setOffset(Math.max(0,offset-30));}}/><Button secondary label="Siguiente" disabled={busy||loading||!page?.hasMore} onPress={()=>{scope.invalidate();setPage(null);setOffset(offset+30);}}/></View>
 </>}
 </ScrollView><Modal visible={Boolean(selected)} transparent animationType="fade" onRequestClose={()=>{if(!busy)setSelection(null);}}><View style={{flex:1,backgroundColor:'rgba(0,0,0,.5)',justifyContent:'center',padding:20}}><ScrollView style={{maxHeight:'90%'}} contentContainerStyle={s.card}>{selected&&<><Text accessibilityRole="header" style={s.title}>{actionLabels[selected.decision]}</Text><Text style={s.title}>{selected.detail.application.agency.tradeName}</Text>{selected.detail.logoUrl&&<Image source={{uri:selected.detail.logoUrl}} accessible accessibilityLabel="Logo privado de la inmobiliaria para revisión" style={{width:110,height:110,borderRadius:16}}/>}{selected.kind==='recovery'&&<AgencyTextField label="ID de la cuenta del nuevo administrador" value={newAdminId} onChangeText={setNewAdminId} editable={!busy} maxLength={36}/>}<Notice>{selected.kind==='recovery'?'Comprueba la identidad del nuevo responsable y registra la evidencia en el motivo. Su correo debe estar confirmado y su cuenta activa. La cartera seguirá pausada; el sello, los procesos terminados y las autorizaciones retiradas no se restauran.':selected.kind==='application'?selected.decision==='approve'?'Permite operar y asigna al responsable como administrador de esta inmobiliaria. No concede verificación.':selected.decision==='suspend'?'Suspende la operativa empresarial y retira la verificación vigente. No se restaurará al recuperar la agencia.':'Esta decisión afecta la aprobación inicial; el motivo será visible al solicitante.':selected.decision==='grant'?'Concede el check verde y permite publicación directa de nuevos envíos válidos de esta agencia. No publica automáticamente borradores o anuncios pendientes.':selected.decision==='revoke'?'Retira el check verde. Los próximos envíos requieren aprobación individual. Conserva las publicaciones ya aprobadas.':'Esta decisión afecta la solicitud de verificación. La agencia sigue operando sin publicación directa.'}</Notice><AgencyTextField label="Motivo visible al solicitante" value={note} onChangeText={setNote} editable={!busy} multiline maxLength={1000}/>{issue&&<Notice error>{issue}</Notice>}<Button label={`Confirmar: ${actionLabels[selected.decision]}`} onPress={()=>void confirm()} loading={busy}/><Button label="Cancelar" secondary onPress={()=>setSelection(null)} disabled={busy}/></>}</ScrollView></View></Modal></SafeAreaView>;
}
