import {router,useLocalSearchParams} from 'expo-router';
import {useCallback,useRef,useState} from 'react';
import {ScrollView,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useAuth} from '../auth/AuthProvider';
import {useAgencyWorkspace} from '../agencies/AgencyProvider';
import {createAgencyDealRepository} from '../agencies/deals/repository';
import {useFollowupScope,type FollowupCapture} from '../agencies/deals/useFollowupScope';
import {followupError,dealStageLabel} from '../agencies/deals/domain';
import type {AgencyDeal,AgencyTask,AgencyFollowupEvent,SaveAgencyTask} from '../agencies/deals/types';
import type {AgencyMembership} from '../agencies/types';
import type {AgencyVisit} from '../agencies/scheduling/types';
import {visitOutcomeLabel} from '../agencies/scheduling/domain';
import {havanaDateTime,havanaVisitInstant,NEGOTIATION_TIME_ZONE} from '../negotiations/domain';
import {createMessageId,isUuid} from '../messaging/domain';
import {supabase} from '../lib/supabase';
import {Button,Notice,PageTitle,Pill} from '../components/ui';
import {useAgencyFormStyles} from '../components/agencies/AgencyRegistrationFields';
import {AgencyProposalPanel} from '../components/agencies/AgencyProposalPanel';
import {VisitDateTimeFields} from '../components/negotiations/VisitDateTimeFields';
const repository=supabase?createAgencyDealRepository(supabase):null;

const format=(date:string)=>new Date(date).toLocaleString('es',{timeZone:NEGOTIATION_TIME_ZONE});
const eventLabel:Record<string,string>={task_saved:'Tarea guardada',task_unassigned:'Tarea pasó a la cola',task_assigned:'Tarea asignada',task_finished:'Tarea resuelta',task_terminated:'Tarea terminada',stage_changed:'Etapa cambiada',deal_assigned:'Responsable del caso cambiado',external_notification_created:'Comunicación pendiente creada'};
export default function AgencyDealScreen(){const a=useAuth(),w=useAgencyWorkspace(),{id}=useLocalSearchParams<{id:string}>();return <Deal key={`${a.user?.id}:${a.session?.access_token}:${w.activeAgencyId}:${w.generation}:${id}`} id={id}/>;}
function Deal({id}:{id:string}){
 const w=useAgencyWorkspace(),{styles:s,colors}=useAgencyFormStyles();
 const [deal,setDeal]=useState<AgencyDeal|null>(null),[tasks,setTasks]=useState<AgencyTask[]>([]),[visits,setVisits]=useState<AgencyVisit[]>([]),[events,setEvents]=useState<AgencyFollowupEvent[]>([]),[members,setMembers]=useState<AgencyMembership[]>([]),[moreMembers,setMoreMembers]=useState(false),[conversationId,setConversationId]=useState<string|null>(null);
 const [moreTasks,setMoreTasks]=useState(false),[moreVisits,setMoreVisits]=useState(false),[moreEvents,setMoreEvents]=useState(false),[busy,setBusy]=useState(false),[issue,setIssue]=useState(''),[lostConfirm,setLostConfirm]=useState(false);
 const [title,setTitle]=useState(''),[due,setDue]=useState(false),[date,setDate]=useState(havanaDateTime().date),[time,setTime]=useState('10:00'),[taskAssignee,setTaskAssignee]=useState<string|null>(null),[editing,setEditing]=useState<AgencyTask|null>(null),[composer,setComposer]=useState(false);
 const lock=useRef(false),pending=useRef<{run:(c:ReturnType<FollowupCapture>,request:string)=>Promise<unknown>;request:string}|null>(null);
 const allowed=w.ready&&!!w.activeAgency&&!!w.membership;
 const coordinate=w.membership?.role==='admin'||w.membership?.role==='coordinator';
 const operational=w.enabled&&w.activeAgency?.state==='approved';
 const live=operational&&!!deal&&!deal.closedReason&&deal.stage!=='lost'&&deal.stage!=='won';
 const load=useCallback(async(capture:FollowupCapture)=>{if(!repository||!allowed)return;let c:ReturnType<FollowupCapture>|undefined;try{if(!isUuid(id))throw Error('Expediente inválido.');c=capture(true);const d=await repository.get(id,c),t=await repository.listTasks({dealId:id,offset:0},c),v=await repository.visits(id,0,c),e=await repository.history(id,0,c),team=await w.repository!.listMembers(0,c),chat=await repository.conversationId(id,c);c.checkpoint();setDeal(d);setTasks(t.items);setMoreTasks(t.hasMore);setVisits(v.items);setMoreVisits(v.hasMore);setEvents(e.items);setMoreEvents(e.hasMore);setMembers(team.items);setMoreMembers(team.hasMore);setConversationId(chat);setIssue('');}catch(e){try{c?.checkpoint();setDeal(null);setTasks([]);setVisits([]);setEvents([]);setIssue(followupError(e));}catch{}}finally{c?.release();}},[allowed,id,w.repository]);
 const clear=useCallback(()=>{setDeal(null);setTasks([]);setVisits([]);setEvents([]);setMembers([]);setMoreTasks(false);setMoreVisits(false);setMoreEvents(false);setMoreMembers(false);setConversationId(null);setBusy(false);setIssue('');setComposer(false);setEditing(null);setTitle('');setDue(false);setTaskAssignee(null);setLostConfirm(false);pending.current=null;},[]);
 const scope=useFollowupScope(load,clear),capture=useCallback((write=false)=>scope.capture(false,write),[scope.capture]);
 async function act(run:(c:ReturnType<FollowupCapture>,request:string)=>Promise<unknown>,refresh=true,write=true){if(lock.current)return;lock.current=true;setBusy(true);setIssue('');let c:ReturnType<FollowupCapture>|undefined;try{c=scope.capture(false,write);if(!pending.current)pending.current={run,request:createMessageId()};await pending.current.run(c,pending.current.request);c.checkpoint();pending.current=null;setComposer(false);setEditing(null);setTitle('');setLostConfirm(false);if(refresh)await load(scope.capture);}catch(e){try{c?.checkpoint();setIssue(followupError(e));}catch{}}finally{c?.release();lock.current=false;if(scope.isActive())setBusy(false);}}
 async function page(kind:'tasks'|'visits'|'events'|'members'){if(!repository)return;await act(async c=>{if(kind==='tasks'){const p=await repository.listTasks({dealId:id,offset:tasks.length},c);c.checkpoint();setTasks(old=>[...old,...p.items]);setMoreTasks(p.hasMore);}else if(kind==='visits'){const p=await repository.visits(id,visits.length,c);c.checkpoint();setVisits(old=>[...old,...p.items]);setMoreVisits(p.hasMore);}else if(kind==='events'){const p=await repository.history(id,events.length,c);c.checkpoint();setEvents(old=>[...old,...p.items]);setMoreEvents(p.hasMore);}else{const p=await w.repository!.listMembers(members.length,c);c.checkpoint();setMembers(old=>[...old,...p.items]);setMoreMembers(p.hasMore);}},false,false);}
 function edit(t?:AgencyTask){setEditing(t??null);setTitle(t?.title??'');setTaskAssignee(t?t.assigneeId:deal?.assigneeId??null);setDue(!!t?.dueAt);if(t?.dueAt){const wall=havanaDateTime(new Date(t.dueAt));setDate(wall.date);setTime(wall.time);}setComposer(true);}
 function save(){if(!deal||!repository)return;let payload:Omit<SaveAgencyTask,'clientRequestId'>;try{payload={dealId:id,title,assigneeId:taskAssignee,dueAt:due?havanaVisitInstant(date,time):null,...(editing?{id:editing.id,expectedVersion:editing.version}:{})};}catch(e){setIssue(followupError(e));return;}void act((c,clientRequestId)=>repository.saveTask({...payload,clientRequestId},c));}
 const disabled=busy||!!pending.current;
 const responsible=deal?.assigneeId===w.membership?.userId?'Tú':members.find(m=>m.userId===deal?.assigneeId)?.displayName??(deal?.assigneeId?'Miembro del equipo':'Sin asignación');
 return <SafeAreaView style={s.safe}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}><PageTitle title="Expediente privado" subtitle={w.activeAgency?.tradeName??'Selecciona una inmobiliaria'} back fallback="/agency-deals"/>
 {!allowed?<Notice>Selecciona una inmobiliaria aprobada con una membresía activa.</Notice>:<>
 {!operational&&<Notice>Solo lectura: el historial se conserva y las operaciones están pausadas.</Notice>}
 {issue?<Notice error>{issue}</Notice>:null}
 <Button secondary label="Actualizar expediente" disabled={disabled} onPress={()=>void load(scope.capture)}/>
 {pending.current&&<><Notice>Conservamos el intento con su contenido original.</Notice><Button label="Reintentar acción" loading={busy} onPress={()=>void act(pending.current!.run)}/><Button secondary label="Descartar intento" disabled={busy} onPress={()=>{pending.current=null;setIssue('');}}/></>}
 {deal&&<>
 <View style={s.card}><Text style={s.title}>{deal.buyerName}</Text><Text style={s.copy}>{deal.propertyTitle}</Text>{deal.privateContact?.phone&&<Text selectable style={s.copy}>{deal.privateContact.phone}</Text>}<Text style={s.copy}>{dealStageLabel[deal.stage]} · Responsable: {responsible}</Text>{deal.closedReason&&<Notice>Este seguimiento terminó · {deal.closedReason}. Las comunicaciones pendientes se completan por separado.</Notice>}
 {conversationId&&<Button secondary label="Abrir conversación de este interesado" onPress={()=>router.push({pathname:'/agency-conversation/[id]',params:{id:conversationId,agencyId:deal.agencyId}})}/>}
 <Button secondary label="Ver interesados de esta vivienda" onPress={()=>router.push({pathname:'/agency-deals',params:{propertyId:deal.propertyId}})}/>
 {coordinate&&live&&<><Text style={s.title}>Asignar responsable</Text><Notice>La asignación conserva las citas confirmadas y comprueba la agenda del nuevo responsable.</Notice><Button label="Tomar este caso" disabled={disabled||deal.assigneeId===w.membership?.userId} onPress={()=>void act((c,clientRequestId)=>repository!.assign({dealId:id,userId:c.userId,expectedVersion:deal.version,clientRequestId},c))}/>{members.filter(m=>m.userId!==deal.buyerId).map(m=><Button key={m.userId} secondary label={`Asignar a ${m.displayName??'miembro del equipo'}`} disabled={disabled||deal.assigneeId===m.userId} onPress={()=>void act((c,clientRequestId)=>repository!.assign({dealId:id,userId:m.userId,expectedVersion:deal.version,clientRequestId},c))}/>)}{moreMembers&&<Button secondary label="Ver más miembros" disabled={disabled} onPress={()=>void page('members')}/>}</>}
 </View>
 {live&&<View style={s.card}><Text style={s.title}>Etapa del interesado</Text><Notice>La etapa describe este seguimiento. Registrar «Visitado» no acredita el resultado de ninguna cita; complétalo en Visitas.</Notice><View style={s.wrap}>{(['inquiry','visit_proposed','visit_confirmed','visited','offer'] as const).map(stage=><Pill key={stage} label={dealStageLabel[stage]} active={deal.stage===stage} onPress={()=>{if(!disabled&&deal.stage!==stage)void act((c,clientRequestId)=>repository!.setStage({dealId:id,stage,expectedVersion:deal.version,clientRequestId},c));}}/>)}</View>
 {lostConfirm?<><Notice error>Terminar el interés cancela las propuestas vigentes, las próximas citas y los seguimientos ordinarios de este interesado. Las citas realizadas conservan su historial. Este expediente no se reabre al cambiar de etapa.</Notice><Button label="Confirmar que terminó el interés" disabled={disabled} onPress={()=>void act((c,clientRequestId)=>repository!.setStage({dealId:id,stage:'lost',expectedVersion:deal.version,clientRequestId},c))}/><Button secondary label="Seguir trabajando este interés" disabled={disabled} onPress={()=>setLostConfirm(false)}/></>:<Button secondary label="Terminar este interés" disabled={disabled} onPress={()=>setLostConfirm(true)}/>}</View>}
 <Button label="Solicitar cierre de venta" disabled={!live||disabled} onPress={()=>router.push({pathname:'/agency-closures',params:{dealId:id}})}/>
 <AgencyProposalPanel onRequestClosure={live?()=>router.push({pathname:'/agency-closures',params:{dealId:id}}):undefined} key={`${id}:${deal.version}`} conversation={{dealId:id,buyerId:deal.buyerId,assigneeId:deal.assigneeId,canSend:live}} actorId={w.membership!.userId} staff capture={capture} external={deal.contactKind==='external'} onChanged={()=>load(scope.capture)}/>
 <View style={s.card}><Text style={s.title}>Visitas y resultados</Text>{visits.map(v=><View key={v.proposalId} style={s.card}><Text style={s.copy}>{format(v.startsAt)} — {format(v.endsAt)} · {visitOutcomeLabel(v.outcome)}</Text>{operational&&v.outcome==='unrecorded'&&(['performed','no_show','cancelled'] as const).map(outcome=><Button key={outcome} secondary label={visitOutcomeLabel(outcome)} disabled={disabled||outcome!=='cancelled'&&Date.parse(v.startsAt)>Date.now()} onPress={()=>void act((c,clientRequestId)=>repository!.scheduling.recordOutcome({proposalId:v.proposalId,outcome,expectedVersion:v.version,clientRequestId},c))}/>)}</View>)}{!visits.length&&<Text style={s.copy}>Sin visitas confirmadas.</Text>}{moreVisits&&<Button secondary label="Visitas anteriores" disabled={disabled} onPress={()=>void page('visits')}/>}</View>
 <View style={s.card}><Text style={s.title}>Próximas acciones</Text>{tasks.map(t=><View key={t.id} style={s.card}><Text style={s.title}>{t.title}</Text><Text style={s.copy}>{t.kind==='external_notification'?'Comunicación externa pendiente':'Seguimiento'} · {t.state==='open'?'Pendiente':t.state==='done'?'Completada':'Cancelada'} · {t.assigneeId===w.membership?.userId?'Responsable: tú':t.assigneeId?'Asignada al responsable del caso':'En cola de asignación'}{t.dueAt?' · '+format(t.dueAt):''}</Text>{t.reason&&<Text style={s.copy}>Motivo: {t.reason}</Text>}{operational&&t.state==='open'&&(coordinate||t.assigneeId===w.membership?.userId)&&<>{(live||t.kind==='external_notification'&&coordinate)&&<Button secondary label="Editar tarea" disabled={disabled} onPress={()=>edit(t)}/>}<Button label={t.kind==='external_notification'?'Registrar comunicación realizada':'Completar tarea'} disabled={disabled} onPress={()=>void act((c,clientRequestId)=>repository!.finishTask({taskId:t.id,state:'done',expectedVersion:t.version,clientRequestId},c))}/><Button secondary label="Cancelar tarea" disabled={disabled} onPress={()=>void act((c,clientRequestId)=>repository!.finishTask({taskId:t.id,state:'cancelled',expectedVersion:t.version,clientRequestId},c))}/></>}</View>)}{!tasks.length&&<Text style={s.copy}>No hay tareas registradas.</Text>}{moreTasks&&<Button secondary label="Más tareas" disabled={disabled} onPress={()=>void page('tasks')}/>}{live&&<Button label="Añadir seguimiento" disabled={disabled} onPress={()=>edit()}/>}<Notice>Los recordatorios se guardan para su entrega posterior. Registra expresamente las comunicaciones externas realizadas.</Notice>
 {composer&&<><TextInput style={s.input} accessibilityLabel="Título del seguimiento" placeholder="Próxima acción" placeholderTextColor={colors.muted} value={title} maxLength={200} editable={!disabled} onChangeText={setTitle}/>{coordinate&&<View style={s.wrap}><Pill label="Sin asignación" active={taskAssignee===null} onPress={()=>{if(!disabled)setTaskAssignee(null);}}/>{deal.assigneeId&&<Pill label={`Responsable: ${responsible}`} active={taskAssignee===deal.assigneeId} onPress={()=>{if(!disabled)setTaskAssignee(deal.assigneeId);}}/>}</View>}<View style={s.wrap}><Pill label="Sin vencimiento" active={!due} onPress={()=>{if(!disabled)setDue(false);}}/><Pill label="Con vencimiento" active={due} onPress={()=>{if(!disabled)setDue(true);}}/></View>{due&&<VisitDateTimeFields date={date} time={time} disabled={disabled} onDate={setDate} onTime={setTime}/>}<Button label="Guardar tarea" disabled={disabled} onPress={save}/><Button secondary label="Cerrar edición" disabled={disabled} onPress={()=>setComposer(false)}/></>}
 </View>
 <View style={s.card}><Text style={s.title}>Historial del seguimiento</Text>{events.map(e=><Text key={e.id} style={s.copy}>{format(e.createdAt)} · {eventLabel[e.kind]??e.kind}{e.details.title?' · '+e.details.title:''}{e.details.stage?' · '+dealStageLabel[e.details.stage]:''}{e.details.reason?' · '+e.details.reason:''} · Registró: {e.actorId===w.membership?.userId?'Tú':members.find(m=>m.userId===e.actorId)?.displayName??(e.actorId?'Miembro del equipo':'Cuenta eliminada / cambio del sistema')}</Text>)}{moreEvents&&<Button secondary label="Eventos anteriores" disabled={disabled} onPress={()=>void page('events')}/>}</View>
 </>}
 </>}
 </ScrollView></SafeAreaView>;
}
