import {router} from 'expo-router';import {useEffect,useRef,useState} from 'react';import {Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {randomUUID} from 'expo-crypto';
import {Button,EmptyState,Notice,PageTitle,Pill} from '../components/ui';import {colors} from '../theme';import {useAssistedListings} from '../assisted/useAssistedListings';import {assistedError} from '../assisted/domain';import type {AssistedCapabilities,AssistedCollaborator,AssistedCollaboratorInput,AssistedListingRow} from '../assisted/types';import {fixtureCollaborators,fixtureAssistedRows} from '../assisted/fixtures';import {useListingTransfers} from '../transfers/useListingTransfers';import {TransferOfferSheet} from '../components/transfers/TransferOfferSheet';import {usePublicProfile} from '../profiles/usePublicProfile';
const blank:AssistedCollaboratorInput={kind:'owner',privateName:'',privateContact:'',contactChannel:'',accountId:null,linkEvidenceReference:''};
export default function AssistedListingsScreen(){const session=useAssistedListings();return <AssistedBody key={session.sessionKey}/>;}
function AssistedBody(){
 const {auth,repository,run}=useAssistedListings(),demo=!repository,transfers=useListingTransfers('outgoing');
 const [capabilities,setCapabilities]=useState<AssistedCapabilities|null>(null),[collaborators,setCollaborators]=useState<AssistedCollaborator[]>(demo?fixtureCollaborators:[]),[hasMore,setHasMore]=useState(false),[selected,setSelected]=useState<AssistedCollaborator|null>(demo?fixtureCollaborators[0]:null),[rows,setRows]=useState<AssistedListingRow[]>(demo?fixtureAssistedRows:[]),[moreRows,setMoreRows]=useState(false),[picked,setPicked]=useState<string[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[editing,setEditing]=useState<AssistedCollaboratorInput|null>(null),[saving,setSaving]=useState(false),[sheet,setSheet]=useState(false);
 const mutation=useRef<{fingerprint:string;id:string}|null>(null),alive=useRef(true),rowSequence=useRef(0);useEffect(()=>{alive.current=true;return()=>{alive.current=false;rowSequence.current++;};},[]);
 const target=usePublicProfile(selected?.accountId??undefined);
 const fail=(e:unknown)=>{if(alive.current&&!/KH_ACCOUNT_CHANGED/.test(String((e as Error)?.message)))setError(assistedError(e));};
 async function loadCollaborators(append=false){if(!repository)return;setLoading(true);try{const data=await run(c=>repository.collaborators(append?collaborators.length:0,c));if(alive.current){setCollaborators(prev=>append?[...prev,...data.items.filter(x=>!prev.some(y=>y.id===x.id))]:data.items);setHasMore(data.hasMore);}}catch(e){fail(e);}finally{if(alive.current)setLoading(false);}}
 useEffect(()=>{if(!repository||!auth.isOwner)return;void run(c=>repository.capabilities(c)).then(value=>{if(alive.current){setCapabilities(value);if(value.canPrepare)void loadCollaborators();}}).catch(fail);},[repository,auth.isOwner]);
 async function loadRows(c:AssistedCollaborator,append=false){const sequence=++rowSequence.current;setSelected(c);if(!append){setPicked([]);setRows([]);setMoreRows(false);}if(!repository){setRows(c.id===fixtureCollaborators[0].id?fixtureAssistedRows:[]);return;}setLoading(true);try{const page=await run(context=>repository.listings(c.id,append?rows.length:0,context));if(alive.current&&sequence===rowSequence.current){setRows(prev=>append?[...prev,...page.items.filter(x=>!prev.some(y=>y.id===x.id))]:page.items);setMoreRows(page.hasMore);}}catch(e){if(sequence===rowSequence.current)fail(e);}finally{if(alive.current&&sequence===rowSequence.current)setLoading(false);}}
 async function save(){if(!editing||!repository||saving)return;const fingerprint=JSON.stringify(editing);if(mutation.current?.fingerprint!==fingerprint)mutation.current={fingerprint,id:randomUUID()};setSaving(true);setError('');try{const value=await run(c=>repository.saveCollaborator({...editing,clientRequestId:mutation.current!.id},c));if(alive.current){setEditing(null);mutation.current=null;await loadCollaborators();await loadRows(value);}}catch(e){fail(e);}finally{if(alive.current)setSaving(false);}}
 const allowed=demo||auth.isOwner&&capabilities?.canPrepare;
 return <SafeAreaView style={s.safe} edges={['top','bottom','left','right']}><ScrollView contentContainerStyle={s.content}><PageTitle title="Publicación asistida" subtitle="Material autorizado, preparado desde la cuenta oficial." back/>
 {!allowed?<EmptyState icon="lock-closed-outline" title="Cuenta principal oficial" description={auth.isOwner?(error|| (capabilities?'La cuenta oficial protegida no está configurada para esta sesión.':'Comprobando la configuración protegida del servidor.')):'Esta sección está disponible para la cuenta principal oficial de KarmaHouse.'}/>:<>
 {demo?<Notice>Ejemplo local con datos sintéticos. Las acciones de publicación y traspaso se habilitan con la cuenta oficial y el servidor configurado.</Notice>:<Notice>Los contactos, permisos y referencias de esta pantalla son privados. El colaborador decide por separado si acepta la gestión.</Notice>}
 {(error||transfers.state.error)&&<Notice error>{error||transfers.state.error}</Notice>}
 <View style={s.actions}><Button label="Registrar colaborador" disabled={demo} onPress={()=>setEditing({...blank})}/><Button label="Solicitudes enviadas" secondary disabled={demo} onPress={()=>router.push({pathname:'/listing-transfers',params:{scope:'outgoing'}})}/></View>
 <Text style={s.heading}>Colaboradores</Text>
 {collaborators.map(c=><View key={c.id} style={[s.card,selected?.id===c.id&&s.selected]}><Pressable accessibilityRole="button" onPress={()=>void loadRows(c)}><Text style={s.title}>{c.privateName}</Text><Text style={s.detail}>{c.kind==='agency'?'Agencia':c.kind==='manager'?'Gestor':'Propietario'} · {c.state==='active'?'Vigente':'Retirado'}</Text><Text style={s.detail}>{c.privateContact} · {c.contactChannel}</Text><Text selectable style={s.detail}>{c.accountId??'Sin cuenta vinculada'}</Text></Pressable><Button secondary label="Editar vínculo y contacto" disabled={demo} onPress={()=>setEditing({...c,expectedVersion:c.version,clientRequestId:undefined})}/></View>)}
 {hasMore&&<Button label="Más colaboradores" secondary loading={loading} onPress={()=>void loadCollaborators(true)}/>}
 {selected&&<><PageTitle title="Anuncios del colaborador" subtitle={selected.privateName} right={<Button label="Preparar anuncio" disabled={demo||selected.state!=='active'} onPress={()=>router.push({pathname:'/assisted-listing-editor',params:{collaboratorId:selected.id}})}/>}/>
 <Text style={s.detail}>{selected.accountId?`${target.profile?.displayName??'Cuenta vinculada'} · ${selected.accountId}`:'Confirma una cuenta por el canal conocido antes de ofrecer gestión.'}</Text>
 {rows.map(row=><View key={row.id} style={s.card}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:picked.includes(row.id),disabled:!row.eligible}} disabled={!row.eligible} onPress={()=>setPicked(prev=>prev.includes(row.id)?prev.filter(id=>id!==row.id):prev.length<20?[...prev,row.id]:prev)}><Text style={s.title}>{picked.includes(row.id)?'☑':'☐'} {row.title}</Text><Text style={s.detail}>{row.moderation==='approved'?(row.availability==='paused'?'Pausado':'Publicado'):row.moderation==='pending'?'En revisión':row.moderation==='draft'?'Borrador':'Necesita cambios'} · {row.collaboratorReference}</Text><Text style={s.detail}>Última confirmación: {row.lastConfirmedAt?new Date(row.lastConfirmedAt).toLocaleString('es-CU'):'Sin registrar'}</Text>{(!row.lastConfirmedAt||Date.now()-Date.parse(row.lastConfirmedAt)>7*86400000)&&<Notice>Confirma precio y disponibilidad con el colaborador antes de ofrecer la gestión.</Notice>}<Text style={s.detail}>{row.eligible?'Disponible para ofrecer gestión':'No elegible: revisa gestor, estado y autorización.'}</Text></Pressable><View style={s.actions}><Button secondary label="Ver ficha" disabled={demo} onPress={()=>router.push(`/property/${row.id}`)}/><Button secondary label="Procedencia y permiso" disabled={demo} onPress={()=>router.push({pathname:'/assisted-listing-editor',params:{collaboratorId:selected.id,id:row.id}})}/></View></View>)}
 {moreRows&&<Button secondary label="Más anuncios" loading={loading} onPress={()=>void loadRows(selected,true)}/>}
 <Notice>{picked.length} / 20 seleccionados. Puedes enviar otros lotes al mismo colaborador después.</Notice>
 <Button label="Revisar solicitud de gestión" disabled={demo||!capabilities?.canOffer||!selected.accountId||!picked.length||selected.state!=='active'} onPress={()=>setSheet(true)}/>
 {!demo&&!capabilities?.transfersEnabled&&<Notice>La preparación está disponible. Los traspasos siguen desactivados en el servidor.</Notice>}
 <TransferOfferSheet key={picked.join(',')} visible={sheet} recipientId={selected.accountId??''} recipientName={target.profile?.displayName??'Cuenta vinculada'} items={rows.filter(x=>picked.includes(x.id))} busy={transfers.state.busy} error={transfers.state.error||error} onClose={()=>setSheet(false)} onOffer={()=>{if(!selected.accountId||!transfers.controller)return;void transfers.controller.offer({collaboratorId:selected.id,expectedCollaboratorVersion:selected.version,recipientId:selected.accountId,items:rows.filter(x=>picked.includes(x.id)).map(x=>({propertyId:x.id,expectedVersion:x.version,expectedProvenanceVersion:x.provenanceVersion}))}).then(r=>{if(alive.current){setSheet(false);router.push(`/listing-transfer/${r.id}`);}}).catch(fail);}}/>
 </>}
 </>}
 </ScrollView>
 <Modal visible={editing!==null} transparent animationType="slide" onRequestClose={()=>!saving&&setEditing(null)}><View style={s.shade}><ScrollView style={s.modal} contentContainerStyle={s.modalContent}><PageTitle title={editing?.id?'Editar colaborador':'Registrar colaborador'}/><Notice>Confirma la identidad de la cuenta por un canal que ya conoces. El nombre público por sí solo no identifica al destinatario.</Notice>{editing&&<><View style={s.actions}>{(['owner','manager','agency'] as const).map(kind=><Pill key={kind} label={kind==='owner'?'Propietario':kind==='manager'?'Gestor':'Agencia'} active={editing.kind===kind} onPress={()=>setEditing({...editing,kind})}/>)}</View>{(['privateName','privateContact','contactChannel','accountId','linkEvidenceReference'] as const).map(key=><View key={key} style={{gap:6}}><Text style={s.detail}>{{privateName:'Nombre privado',privateContact:'Contacto privado',contactChannel:'Canal conocido',accountId:'UUID exacto de la cuenta (opcional)',linkEvidenceReference:'Referencia privada de confirmación del vínculo'}[key]}</Text><TextInput accessibilityLabel={key} style={s.input} autoCapitalize="none" value={editing[key]??''} maxLength={key==='privateName'?120:key==='privateContact'?200:key==='accountId'?36:500} onChangeText={value=>setEditing({...editing,[key]:value})}/></View>)}<Pill label={editing.state==='withdrawn'?'Colaborador retirado':'Colaborador vigente'} active={editing.state!=='withdrawn'} onPress={()=>setEditing({...editing,state:editing.state==='withdrawn'?'active':'withdrawn'})}/><Text style={s.detail}>Retirar al colaborador pausa sus anuncios y deja sin validez las solicitudes pendientes.</Text></>}{!!error&&<Notice error>{error}</Notice>}<Button label="Guardar colaborador" loading={saving} onPress={()=>void save()}/><Button label="Volver" secondary disabled={saving} onPress={()=>setEditing(null)}/></ScrollView></View></Modal>
 </SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},content:{width:'100%',maxWidth:900,alignSelf:'center',padding:20,gap:18,paddingBottom:40},heading:{fontSize:20,fontWeight:'600',color:colors.ink},card:{backgroundColor:colors.white,padding:18,borderRadius:22,gap:14,borderWidth:1,borderColor:colors.white},selected:{borderColor:colors.primary},title:{color:colors.ink,fontSize:17,fontWeight:'600',lineHeight:24},detail:{color:colors.muted,fontSize:14,lineHeight:21},actions:{flexDirection:'row',flexWrap:'wrap',gap:10},shade:{flex:1,backgroundColor:'#0007',justifyContent:'flex-end',alignItems:'center'},modal:{width:'100%',maxWidth:640,maxHeight:'94%',backgroundColor:colors.paper,borderTopLeftRadius:26,borderTopRightRadius:26},modalContent:{padding:24,gap:18,paddingBottom:38},input:{borderWidth:1,borderColor:colors.border,borderRadius:14,padding:13,backgroundColor:colors.white,color:colors.ink,minHeight:48}});
