import {router} from 'expo-router';import {useEffect,useRef,useState} from 'react';import {Modal,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {randomUUID} from 'expo-crypto';
import {useAdminQuery} from '../admin/useAdminQuery';import {AdminPagination,AdminStatus,AdminToolbar,options} from '../components/admin/AdminControls';
import {Button,EmptyState,Notice,PageTitle,Pill} from '../components/ui';import {createThemedStyles} from '../theme';import {useAssistedListings} from '../assisted/useAssistedListings';import {assistedError} from '../assisted/domain';import type {AssistedCapabilities,AssistedCollaborator,AssistedCollaboratorInput,AssistedListingRow} from '../assisted/types';import {fixtureCollaborators,fixtureAssistedRows} from '../assisted/fixtures';import {useListingTransfers} from '../transfers/useListingTransfers';import {TransferOfferSheet} from '../components/transfers/TransferOfferSheet';import {usePublicProfile} from '../profiles/usePublicProfile';
const blank:AssistedCollaboratorInput={kind:'owner',privateName:'',privateContact:'',contactChannel:'',accountId:null,linkEvidenceReference:''};
export default function AssistedListingsScreen(){const session=useAssistedListings();return <AssistedBody key={session.sessionKey}/>;}
function AssistedBody(){
  const { colors,styles: s } = useStyles();
 const {auth,repository,run}=useAssistedListings(),demo=!repository,transfers=useListingTransfers('outgoing');
 const [capabilities,setCapabilities]=useState<AssistedCapabilities|null>(null),[selected,setSelected]=useState<AssistedCollaborator|null>(demo?fixtureCollaborators[0]:null),[picked,setPicked]=useState<string[]>([]),[chosenRows,setChosenRows]=useState<Record<string,AssistedListingRow>>({}),[error,setError]=useState(''),[editing,setEditing]=useState<AssistedCollaboratorInput|null>(null),[saving,setSaving]=useState(false),[sheet,setSheet]=useState(false);
 const [tab,setTab]=useState<'collaborators'|'listings'>('collaborators'),[query,setQuery]=useState(''),[filters,setFilters]=useState<Record<string,string>>({}),[rowQuery,setRowQuery]=useState(''),[rowFilters,setRowFilters]=useState<Record<string,string>>({}),[sort,setSort]=useState<'newest'|'oldest'|'name'>('newest');
 const allowed=demo||auth.isOwner&&capabilities?.canPrepare;
 const collaboratorList=useAdminQuery('assistedCollaborators',query,filters,sort,!!allowed&&!demo);
 const rowList=useAdminQuery('assistedListings',rowQuery,{...rowFilters,collaboratorId:selected?.id??''},sort,!!allowed&&!demo&&!!selected);
 const collaborators=demo?fixtureCollaborators:collaboratorList.items as AssistedCollaborator[],rows=demo?(selected?.id===fixtureCollaborators[0].id?fixtureAssistedRows:[]):rowList.items as AssistedListingRow[],loading=tab==='collaborators'?collaboratorList.loading:rowList.loading;
 const visibleEditing=allowed&&auth.isOwner?editing:null;
 const offeredRows=picked.map(id=>chosenRows[id]).filter(Boolean);
 const mutation=useRef<{fingerprint:string;id:string}|null>(null),alive=useRef(true),rowSequence=useRef(0);useEffect(()=>{alive.current=true;return()=>{alive.current=false;rowSequence.current++;};},[]);
 const target=usePublicProfile(selected?.accountId??undefined);
 const fail=(e:unknown)=>{if(alive.current&&!/KH_ACCOUNT_CHANGED/.test(String((e as Error)?.message)))setError(assistedError(e));};
 const loadCollaborators=collaboratorList.reload;
 useEffect(()=>{if(!repository||!auth.isOwner)return;void run(c=>repository.capabilities(c)).then(value=>{if(alive.current)setCapabilities(value);}).catch(fail);},[repository,auth.isOwner]);
 useEffect(()=>{if(!selected)return;const fresh=collaborators.find(c=>c.id===selected.id);if(fresh&&fresh.version!==selected.version){setSelected(fresh);setPicked([]);setChosenRows({});}},[collaborators,selected]);
 function loadRows(c:AssistedCollaborator){setSelected(c);setPicked([]);setChosenRows({});setTab('listings');}
 function pick(row:AssistedListingRow){if(picked.includes(row.id)){setPicked(p=>p.filter(id=>id!==row.id));setChosenRows(p=>{const next={...p};delete next[row.id];return next;});}else if(picked.length<20){setPicked(p=>[...p,row.id]);setChosenRows(p=>({...p,[row.id]:row}));}}
 async function save(){if(!editing||!repository||!auth.isOwner||!capabilities?.canPrepare||saving)return;const fingerprint=JSON.stringify(editing);if(mutation.current?.fingerprint!==fingerprint)mutation.current={fingerprint,id:randomUUID()};setSaving(true);setError('');try{const value=await run(c=>repository.saveCollaborator({...editing,clientRequestId:mutation.current!.id},c));if(alive.current){setEditing(null);mutation.current=null;await loadCollaborators();await loadRows(value);}}catch(e){fail(e);}finally{if(alive.current)setSaving(false);}}
 return <SafeAreaView style={s.safe} edges={['top','bottom','left','right']}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={tab==='collaborators'?collaboratorList.refreshing:rowList.refreshing} enabled={!demo&&!saving&&!sheet&&!editing} onRefresh={()=>{if(!saving&&!sheet&&!editing)void (tab==='collaborators'?collaboratorList.refresh():rowList.refresh());}} tintColor={colors.primary}/>}><PageTitle title="Publicación asistida" subtitle="Material autorizado, preparado desde la cuenta oficial." back/>
 {!allowed?<EmptyState icon="lock-closed-outline" title="Cuenta principal oficial" description={auth.isOwner?(error|| (capabilities?'La cuenta oficial protegida no está configurada para esta sesión.':'Comprobando la configuración protegida del servidor.')):'Esta sección está disponible para la cuenta principal oficial de KarmaHouse.'}/>:<>
 {demo?<Notice>Ejemplo local con datos sintéticos. Las acciones de publicación y traspaso se habilitan con la cuenta oficial y el servidor configurado.</Notice>:<Notice>Los contactos, permisos y referencias de esta pantalla son privados. El colaborador decide por separado si acepta la gestión.</Notice>}
 {(error||transfers.state.error)&&<Notice error>{error||transfers.state.error}</Notice>}
 <View style={s.actions}><Button label="Registrar colaborador" disabled={demo} onPress={()=>setEditing({...blank})}/><Button label="Solicitudes enviadas" secondary disabled={demo} onPress={()=>router.push({pathname:'/listing-transfers',params:{scope:'outgoing'}})}/></View>
 <View style={s.actions}><Pill label="Colaboradores" active={tab==='collaborators'} onPress={()=>setTab('collaborators')}/><Pill label="Anuncios" active={tab==='listings'} onPress={()=>setTab('listings')}/></View>
 {tab==='collaborators'?<>
 <AdminToolbar query={query} onSearch={setQuery} filters={filters} onFilters={setFilters} sort={sort} onSort={v=>setSort(v as typeof sort)} disabled={demo||saving} fields={[{key:'kind',label:'Tipo',options:options({owner:'Propietario',manager:'Gestor',agency:'Inmobiliaria'})},{key:'state',label:'Estado',options:options({active:'Vigente',withdrawn:'Retirado'})},{key:'link',label:'Cuenta vinculada',options:options({linked:'Vinculada',unlinked:'Sin vínculo'})}]}/>
 {collaboratorList.error&&<Notice error>{collaboratorList.error}</Notice>}
 <Text style={s.heading}>Colaboradores</Text>
 {collaborators.map(c=><View key={c.id} style={[s.card,selected?.id===c.id&&s.selected]}><Pressable accessibilityRole="button" onPress={()=>void loadRows(c)}><Text style={s.title}>{c.privateName}</Text><Text style={s.detail}>{c.kind==='agency'?'Agencia':c.kind==='manager'?'Gestor':'Propietario'} · {c.state==='active'?'Vigente':'Retirado'}</Text><Text style={s.detail}>{c.privateContact} · {c.contactChannel}</Text><Text selectable style={s.detail}>{c.accountId??'Sin cuenta vinculada'}</Text></Pressable><Button secondary label="Editar vínculo y contacto" disabled={demo} onPress={()=>setEditing({...c,expectedVersion:c.version,clientRequestId:undefined})}/></View>)}
 {!collaborators.length&&!loading&&!collaboratorList.error&&<EmptyState title="Sin colaboradores" description="Registra un colaborador o cambia los filtros."/>}
 {!demo&&<AdminPagination {...collaboratorList} loading={loading||saving}/>}
 </>:selected?<>
 <PageTitle title="Anuncios del colaborador" subtitle={selected.privateName} right={<Button label="Preparar anuncio" disabled={demo||selected.state!=='active'} onPress={()=>router.push({pathname:'/assisted-listing-editor',params:{collaboratorId:selected.id}})}/>}/>
 <AdminToolbar query={rowQuery} onSearch={setRowQuery} filters={rowFilters} onFilters={setRowFilters} sort={sort} onSort={v=>setSort(v as typeof sort)} disabled={demo||saving} fields={[{key:'moderation',label:'Revisión',options:options({draft:'Borrador',pending:'En revisión',approved:'Aprobado',rejected:'Necesita cambios'})},{key:'availability',label:'Disponibilidad',options:options({active:'Activo',paused:'Pausado',sold:'Cerrado'})},{key:'eligible',label:'Solicitud de gestión',options:options({true:'Elegibles',false:'No elegibles'})}]}/>
 {rowList.error&&<Notice error>{rowList.error}</Notice>}
 <Text style={s.detail}>{selected.accountId?`${target.profile?.displayName??'Cuenta vinculada'} · ${selected.accountId}`:'Confirma una cuenta por el canal conocido antes de ofrecer gestión.'}</Text>
 {rows.map(row=><View key={row.id} style={s.card}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:picked.includes(row.id),disabled:!row.eligible}} disabled={!row.eligible} onPress={()=>pick(row)}><Text style={s.title}>{picked.includes(row.id)?'☑':'☐'} {row.title}</Text><Text style={s.detail}>{row.moderation==='approved'?(row.availability==='paused'?'Pausado':'Publicado'):row.moderation==='pending'?'En revisión':row.moderation==='draft'?'Borrador':'Necesita cambios'} · {row.collaboratorReference}</Text><Text style={s.detail}>Última confirmación: {row.lastConfirmedAt?new Date(row.lastConfirmedAt).toLocaleString('es-CU'):'Sin registrar'}</Text>{(!row.lastConfirmedAt||Date.now()-Date.parse(row.lastConfirmedAt)>7*86400000)&&<Notice>Confirma precio y disponibilidad con el colaborador antes de ofrecer la gestión.</Notice>}<Text style={s.detail}>{row.eligible?'Disponible para ofrecer gestión':'No elegible: revisa gestor, estado y autorización.'}</Text></Pressable><View style={s.actions}><Button secondary label="Ver ficha" disabled={demo} onPress={()=>router.push(`/property/${row.id}`)}/><Button secondary label="Procedencia y permiso" disabled={demo} onPress={()=>router.push({pathname:'/assisted-listing-editor',params:{collaboratorId:selected.id,id:row.id}})}/></View></View>)}
 {!rows.length&&!loading&&!rowList.error&&<EmptyState title="Sin anuncios en esta vista" description="Prepara un anuncio autorizado o cambia los filtros."/>}
 {!demo&&<AdminPagination {...rowList} loading={loading||saving}/>}

 <Notice>{picked.length} / 20 seleccionados. Puedes enviar otros lotes al mismo colaborador después.</Notice>
 <Button label="Revisar solicitud de gestión" disabled={demo||!capabilities?.canOffer||!selected.accountId||!picked.length||selected.state!=='active'} onPress={()=>setSheet(true)}/>
 {!demo&&!capabilities?.transfersEnabled&&<Notice>La preparación está disponible. Los traspasos siguen desactivados en el servidor.</Notice>}
 <TransferOfferSheet key={picked.join(',')} visible={sheet} recipientId={selected.accountId??''} recipientName={target.profile?.displayName??'Cuenta vinculada'} items={offeredRows} busy={transfers.state.busy} error={transfers.state.error||error} onClose={()=>setSheet(false)} onOffer={()=>{if(!selected.accountId||!transfers.controller)return;void transfers.controller.offer({collaboratorId:selected.id,expectedCollaboratorVersion:selected.version,recipientId:selected.accountId,items:offeredRows.map(x=>({propertyId:x.id,expectedVersion:x.version,expectedProvenanceVersion:x.provenanceVersion}))}).then(r=>{if(alive.current){setSheet(false);router.push(`/listing-transfer/${r.id}`);}}).catch(fail);}}/>
 </>:<EmptyState title="Elige un colaborador" description="Abre un colaborador para consultar sus anuncios."/>}
 </>}
 </ScrollView>
 <Modal visible={visibleEditing!==null} transparent animationType="slide" onRequestClose={()=>!saving&&setEditing(null)}><View style={s.shade}><ScrollView style={s.modal} contentContainerStyle={s.modalContent}><PageTitle title={visibleEditing?.id?'Editar colaborador':'Registrar colaborador'}/><Notice>Confirma la identidad de la cuenta por un canal que ya conoces. El nombre público por sí solo no identifica al destinatario.</Notice>{visibleEditing&&<><View style={s.actions}>{(['owner','manager','agency'] as const).map(kind=><Pill key={kind} label={kind==='owner'?'Propietario':kind==='manager'?'Gestor':'Agencia'} active={visibleEditing.kind===kind} onPress={()=>setEditing({...visibleEditing,kind})}/>)}</View>{(['privateName','privateContact','contactChannel','accountId','linkEvidenceReference'] as const).map(key=><View key={key} style={{gap:6}}><Text style={s.detail}>{{privateName:'Nombre privado',privateContact:'Contacto privado',contactChannel:'Canal conocido',accountId:'UUID exacto de la cuenta (opcional)',linkEvidenceReference:'Referencia privada de confirmación del vínculo'}[key]}</Text><TextInput accessibilityLabel={key} style={s.input} autoCapitalize="none" value={visibleEditing[key]??''} maxLength={key==='privateName'?120:key==='privateContact'?200:key==='accountId'?36:500} onChangeText={value=>setEditing({...visibleEditing,[key]:value})}/></View>)}<Pill label={visibleEditing.state==='withdrawn'?'Colaborador retirado':'Colaborador vigente'} active={visibleEditing.state!=='withdrawn'} onPress={()=>setEditing({...visibleEditing,state:visibleEditing.state==='withdrawn'?'active':'withdrawn'})}/><Text style={s.detail}>Retirar al colaborador pausa sus anuncios y deja sin validez las solicitudes pendientes.</Text></>}{!!error&&<Notice error>{error}</Notice>}<Button label="Guardar colaborador" loading={saving} onPress={()=>void save()}/><Button label="Volver" secondary disabled={saving} onPress={()=>setEditing(null)}/></ScrollView></View></Modal>
 </SafeAreaView>;
}
const useStyles = createThemedStyles(colors => StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},content:{width:'100%',maxWidth:900,alignSelf:'center',padding:20,gap:18,paddingBottom:40},heading:{fontSize:20,fontWeight:'600',color:colors.ink},card:{backgroundColor:colors.surface,padding:18,borderRadius:22,gap:14,borderWidth:1,borderColor:colors.border},selected:{borderColor:colors.primary},title:{color:colors.ink,fontSize:17,fontWeight:'600',lineHeight:24},detail:{color:colors.muted,fontSize:14,lineHeight:21},actions:{flexDirection:'row',flexWrap:'wrap',gap:10},shade:{flex:1,backgroundColor:colors.photoOverlay,justifyContent:'flex-end',alignItems:'center'},modal:{width:'100%',maxWidth:640,maxHeight:'94%',backgroundColor:colors.paper,borderTopLeftRadius:26,borderTopRightRadius:26},modalContent:{padding:24,gap:18,paddingBottom:38},input:{borderWidth:1,borderColor:colors.border,borderRadius:14,padding:13,backgroundColor:colors.surface,color:colors.ink,minHeight:48}}));
