import {router,useLocalSearchParams} from 'expo-router';import {useEffect,useRef,useState} from 'react';import {ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {Button,EmptyState,Notice,PageTitle} from '../components/ui';import ListingForm from '../components/ListingForm';import {useAssistedListings} from '../assisted/useAssistedListings';import type {AssistedProvenance} from '../assisted/types';import {assistedError,validateDraftProvenance} from '../assisted/domain';import {useListing} from '../catalog/useCatalog';import {toDraft} from './EditScreen';import {useMarketplace} from '../state/MarketplaceProvider';import {useListingManagement} from '../transfers/useListingManagement';import {createThemedStyles} from '../theme';
export default function AssistedListingEditorScreen(){const session=useAssistedListings();return <EditorBody key={session.sessionKey}/>;}
function EditorBody(){
  const { styles: s } = useStyles();
 const params=useLocalSearchParams<{collaboratorId?:string;id?:string}>(),id=params.id,collaboratorId=params.collaboratorId??'',{auth,repository,run}=useAssistedListings(),marketplace=useMarketplace(),{listing}=useListing(id),management=useListingManagement(id);
 const [step,setStep]=useState<'permission'|'listing'>('permission'),[error,setError]=useState(''),[ready,setReady]=useState(!id),[allowed,setAllowed]=useState(false),[proof,setProof]=useState<AssistedProvenance>({collaboratorId,collaboratorReference:'',sourceChannel:'directo',receivedAt:'',consentText:'',consentVersion:'1',consentAt:'',evidenceReference:'',lastConfirmedAt:''});
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(!repository||!auth.isOwner)return;void run(async c=>{const cap=await repository.capabilities(c);if(!cap.canPrepare)throw Error('KH_OFFICIAL_ACCOUNT_REQUIRED');const existing=id?await repository.provenance(id,c):null;return existing;}).then(existing=>{if(alive.current){setAllowed(true);if(existing)setProof(existing);setReady(true);}}).catch(e=>{if(alive.current&&!/KH_ACCOUNT_CHANGED/.test(String(e?.message))){setError(assistedError(e));setReady(true);}});},[repository,id,auth.isOwner]);
 const fields:{key:keyof AssistedProvenance;label:string;max:number;multiline?:boolean}[]=[{key:'collaboratorReference',label:'Referencia única del colaborador',max:100},{key:'sourceChannel',label:'Canal de entrega del material',max:40},{key:'sourceReference',label:'Referencia privada del material (opcional)',max:500},{key:'receivedAt',label:'Fecha y hora de recepción',max:40},{key:'consentText',label:'Autorización para texto, fotos, difusión y consultas',max:2000,multiline:true},{key:'consentVersion',label:'Versión del texto de autorización',max:100},{key:'consentAt',label:'Fecha y hora del permiso',max:40},{key:'evidenceReference',label:'Referencia privada de la evidencia del permiso',max:500},{key:'lastConfirmedAt',label:'Última confirmación de precio y disponibilidad',max:40}];
 if(!repository||!auth.isOwner||!allowed)return <SafeAreaView style={s.safe}><View style={s.header}><PageTitle title="Preparar anuncio asistido" back/><EmptyState icon="lock-closed-outline" title={!repository?'Preparación con la cuenta oficial':'Acceso a publicación asistida'} description={!repository?'El ejemplo local no publica material real. Conecta el servidor y la cuenta principal oficial para preparar una ficha.':error||'Comprobando el acceso protegido del servidor.'}/></View></SafeAreaView>;
 return <SafeAreaView style={s.safe} edges={['top','left','right']}><View style={s.header}><PageTitle title={id?'Procedencia y permiso':'Preparar anuncio asistido'} back subtitle="La autorización y la ficha se guardan juntas."/>{!!error&&<Notice error>{error}</Notice>}</View>
 {!ready?<Notice>Cargando procedencia privada…</Notice>:step==='permission'?<ScrollView contentContainerStyle={s.content}><Notice>Usa material entregado directamente. Las fechas reflejan la recepción y el permiso originales. No se descargan imágenes ni instrucciones desde referencias.</Notice><Text style={s.detail}>Fechas con hora y zona: 2026-10-05T14:00:00-04:00. Registra por separado recepción, permiso y última confirmación.</Text>{fields.map(field=><View key={field.key} style={s.field}><Text style={s.label}>{field.label}</Text><TextInput accessibilityLabel={field.label} value={String(proof[field.key]??'')} autoCapitalize="none" multiline={field.multiline} maxLength={field.max} style={[s.input,field.multiline&&{minHeight:120,textAlignVertical:'top'}]} onChangeText={value=>setProof({...proof,[field.key]:value})}/></View>)}
 {proof.revoked&&<Notice error>El permiso está retirado. Una nueva autorización debe ser posterior a la retirada.</Notice>}
 <Button label="Revisar ficha y material" onPress={()=>{try{setProof(validateDraftProvenance(proof));setError('');setStep('listing');}catch(e){setError(assistedError(e));}}}/>
 {id&&proof.expectedVersion&&<Button label="Retirar permiso y pausar ficha" secondary onPress={()=>{void run(c=>repository.revoke(id,proof.expectedVersion!,c)).then(async()=>{if(alive.current){await marketplace.invalidateListingManagement([id]);router.replace('/assisted-listings');}}).catch(e=>{if(alive.current)setError(assistedError(e));});}}/>}
 </ScrollView>:<>
 <View style={s.header}><Notice>Referencia {proof.collaboratorReference}. Permiso {proof.consentVersion}, recibido {proof.receivedAt}. Antes de publicar, revisa precio, disponibilidad, texto y fotos en la vista previa.</Notice><Button secondary label="Revisar autorización" onPress={()=>setStep('permission')}/></View>
 {id&&(!listing||management.value?.managerId!==auth.user?.id)?<View style={s.header}><Notice error>{management.error??'Solo se puede editar una ficha que sigue gestionada por la cuenta oficial. La procedencia permanece disponible para retirar el permiso.'}</Notice><Button label="Actualizar gestor" secondary onPress={()=>void management.refresh().catch(()=>{})}/></View>:<ListingForm key={`${auth.user?.id}:${id??collaboratorId}`} initialDraft={listing?toDraft(listing):undefined} cloud directPublication submitLabel="Guardar autorización y publicar" draftStorageKey={`karmahouse:draft:${auth.user?.id}:assisted:${id??collaboratorId}`} onCancel={()=>router.back()} onReloadLatest={marketplace.refresh} onSaveDraft={!listing||listing.moderationStatus==='draft'?async draft=>{const saved=await run(c=>repository.save(draft,proof,'draft',listing,c));await marketplace.invalidateListingManagement([saved.id]);}:undefined} onSubmit={async draft=>{const saved=await run(c=>repository.save(draft,proof,'pending',listing,c));await marketplace.invalidateListingManagement([saved.id]);}} onSaved={()=>router.dismissTo('/assisted-listings')}/>}</>}
 </SafeAreaView>;
}
const useStyles = createThemedStyles(colors => StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},header:{padding:20,gap:14,width:'100%',maxWidth:860,alignSelf:'center'},content:{padding:20,paddingBottom:38,gap:20,width:'100%',maxWidth:700,alignSelf:'center'},field:{gap:8},label:{color:colors.ink,fontSize:15,fontWeight:'600'},detail:{color:colors.muted,fontSize:14,lineHeight:22},input:{padding:14,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,color:colors.ink,minHeight:50}}));
