import {router,useLocalSearchParams} from 'expo-router';import {useEffect,useRef,useState} from 'react';import {Image,ScrollView,StyleSheet,Text,View} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import {Button,EmptyState,Notice,PageTitle} from '../components/ui';import {useListingTransfers} from '../transfers/useListingTransfers';import {transferError,transferStateLabel} from '../transfers/domain';import {fixtureTransfer} from '../transfers/fixtures';import {scopedClient,usePrivateSession} from '../assisted/usePrivateSession';import {supabase} from '../lib/supabase';import {useMarketplace} from '../state/MarketplaceProvider';import {colors,formatMoney} from '../theme';
import {createTransferManagementReconciler} from '../transfers/reconcileManagement';
export default function ListingTransferScreen(){const privateSession=usePrivateSession();return <TransferBody key={privateSession.key}/>;}
function TransferBody(){
 const {id}=useLocalSearchParams<{id:string}>(),transfers=useListingTransfers(),demo=!transfers.controller,session=usePrivateSession(),marketplace=useMarketplace();
 const row=demo?fixtureTransfer:transfers.state.opened,[urls,setUrls]=useState<Record<string,string>>({}),[previewError,setPreviewError]=useState(''),[confirmed,setConfirmed]=useState(false),[issue,setIssue]=useState(''),[previewAttempt,setPreviewAttempt]=useState(0),[loadedPhotos,setLoadedPhotos]=useState<Record<string,boolean>>({});const latestUrls=useRef(urls);latestUrls.current=urls;const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(id&&transfers.auth.user)void transfers.controller?.open(id);},[id,transfers.controller,transfers.auth.user?.id,transfers.auth.session?.access_token]);
 useEffect(()=>{
  setUrls({});setLoadedPhotos({});setPreviewError('');setConfirmed(false);if(!supabase||!row||row.effectiveState!=='pending'||![row.recipient.id,row.sourceManagerId].includes(transfers.auth.user?.id??''))return;
  let cancelled=false;const current=row;
  void session.run(async context=>{const authorized=new Set(current.items.flatMap(i=>[...i.snapshot.photo_paths,...(i.snapshot.cover_thumb_path?[i.snapshot.cover_thumb_path]:[])]));if(context.userId===current.sourceManagerId){const client=scopedClient(context);const response=await client.storage.from('property-photos').createSignedUrls([...authorized],300);context.checkpoint();if(response.error||response.data?.some(x=>!x.signedUrl||x.error))throw Error('PREVIEW_UNAVAILABLE');const fresh=await client.rpc('kh_get_listing_transfer',{p_actor_id:context.userId,p_request_id:current.id}).abortSignal(context.signal);context.checkpoint();if(fresh.error||fresh.data?.effectiveState!=='pending'||fresh.data?.requestVersion!==current.requestVersion)throw Error('PREVIEW_UNAVAILABLE');return Object.fromEntries((response.data??[]).map(x=>[x.path!,x.signedUrl]));}const {data,error}=await supabase!.functions.invoke('listing-transfer-preview',{body:{requestId:current.id},headers:{Authorization:`Bearer ${context.accessToken}`},signal:context.signal});context.checkpoint();if(error)throw error;if(data?.requestId!==current.id||data?.requestVersion!==current.requestVersion||data?.expiresIn!==300||!Array.isArray(data.urls))throw Error('PREVIEW_UNAVAILABLE');if(data.urls.some((x:{path:string;signedUrl:string})=>!authorized.has(x.path)||typeof x.signedUrl!=='string'))throw Error('PREVIEW_UNAVAILABLE');return Object.fromEntries(data.urls.map((x:{path:string;signedUrl:string})=>[x.path,x.signedUrl]));}).then(value=>{if(!cancelled&&alive.current)setUrls(value);}).catch(e=>{if(!cancelled&&alive.current&&!/ACCOUNT_CHANGED/.test(String(e?.message)))setPreviewError('No se pudieron revisar todas las imágenes. Actualiza la solicitud antes de aceptar.');});
  const timer=setTimeout(()=>{if(!cancelled){setUrls({});setPreviewError('La revisión privada venció. Actualiza para volver a ver las imágenes.');}},300000);
  return()=>{cancelled=true;clearTimeout(timer);};
 },[row?.id,row?.requestVersion,row?.effectiveState,transfers.auth.user?.id,previewAttempt]);
 const reconcile=useRef(createTransferManagementReconciler());useEffect(()=>{reconcile.current(row,marketplace.invalidateListingManagement);},[row?.id,row?.requestVersion,row?.effectiveState]);
 async function decide(decision:'accept'|'reject'|'cancel'){if(!row||!transfers.controller)return;setIssue('');try{const result=await transfers.controller.decide({requestId:row.id,expectedRequestVersion:row.requestVersion,decision});if(!alive.current)return;setUrls({});if(result.state==='accepted')setConfirmed(false);}catch(e){if(alive.current&&!/ACCOUNT_CHANGED/.test(String((e as Error)?.message)))setIssue(transferError(e));}}
 const hasPhotos=!!row?.items.some(i=>i.snapshot.photo_paths.length>0),imagesReady=!hasPhotos||row?.items.every(i=>i.snapshot.photo_paths.every(path=>!!urls[path]&&!!loadedPhotos[path]));
 return <SafeAreaView style={s.safe} edges={['top','bottom','left','right']}><ScrollView contentContainerStyle={s.content}><PageTitle title="Revisar gestión" subtitle="La decisión aplica al lote completo." back/>
 {demo&&<Notice>Solicitud de ejemplo. Las acciones están desactivadas en la demostración.</Notice>}
 {transfers.state.error&&<Notice error>{transfers.state.error}</Notice>}{!!issue&&<Notice error>{issue}</Notice>}
 {!row?<EmptyState icon="swap-horizontal-outline" title={transfers.state.loading?'Cargando solicitud':'Solicitud no disponible'} description="Solo la cuenta oficial y el destinatario pueden verla." action={<Button secondary label="Actualizar" disabled={demo||!transfers.auth.user} onPress={()=>void transfers.controller?.open(id)}/>}/>:<>
 <View style={s.card}><Text style={s.status}>{transferStateLabel[row.effectiveState]}</Text><Text style={s.title}>{row.items.length} anuncios · {row.recipient.displayName}</Text><Text selectable style={s.detail}>Cuenta: {row.recipient.id}</Text><Text style={s.detail}>Vence el {new Date(row.expiresAt).toLocaleString('es-CU')}</Text><Text style={s.detail}>Ofrecidos por la cuenta principal oficial de KarmaHouse.</Text></View>
 {row.reasonCode&&<Notice error>{transferError(Error(row.reasonCode))}</Notice>}
 <Notice>Al aceptar, podrás editar las fichas y atender consultas nuevas. Los enlaces, fechas de publicación, fotos, favoritos, moderación y disponibilidad se conservan. Las fichas pausadas seguirán pausadas.</Notice>
 <Notice>Las conversaciones, ofertas y visitas anteriores quedan con sus participantes. No recibirás contactos privados ni pruebas de autorización, y la recepción de anuncios no añade reputación por publicación.</Notice>
 {!!previewError&&row.canAccept&&<Notice error>{previewError}</Notice>}
 {row.items.map(item=><View key={item.propertyId} style={s.card}><Text style={s.title}>{item.snapshot.title}</Text><Text style={s.detail}>{item.snapshot.location}, {item.snapshot.province} · {formatMoney(Number(item.snapshot.price))} USD</Text><Text style={s.detail}>{item.snapshot.availability==='paused'?'Pausado':'Activo'} · Publicado el {new Date(item.snapshot.created_at).toLocaleDateString('es-CU')}</Text><Text style={s.detail}>{item.snapshot.description}</Text>
 {row.effectiveState==='pending'&&item.snapshot.photo_paths.length>0&&<ScrollView horizontal contentContainerStyle={s.photos}>{item.snapshot.photo_paths.map(path=>urls[path]?<Image key={`${path}:${urls[path]}`} onLoad={()=>{if(latestUrls.current[path]===urls[path])setLoadedPhotos(value=>value[path]?value:{...value,[path]:true});}} onError={()=>{if(latestUrls.current[path]===urls[path])setPreviewError('Una imagen no se pudo cargar. Actualiza antes de aceptar.');}} source={{uri:urls[path]}} accessibilityLabel={`Foto de ${item.snapshot.title}`} style={s.photo}/>:<View key={path} style={[s.photo,s.placeholder]}><Text style={s.detail}>Vista privada pendiente</Text></View>)}</ScrollView>}
 {row.effectiveState==='accepted'&&<Button secondary label="Abrir anuncio" onPress={()=>router.push(`/property/${item.propertyId}`)}/>}</View>)}
 {row.canAccept&&<><Button label={confirmed?'Aceptación confirmada para mi cuenta':'Confirmar que quiero gestionar todas las fichas'} secondary disabled={transfers.state.busy} onPress={()=>setConfirmed(!confirmed)}/><Button label="Aceptar lote completo" disabled={!confirmed||!imagesReady||!!previewError} loading={transfers.state.busy} onPress={()=>void decide('accept')}/></>}
 {row.canReject&&<Button secondary label="Rechazar solicitud" disabled={transfers.state.busy} onPress={()=>void decide('reject')}/>}{row.canCancel&&<Button secondary label="Cancelar solicitud" disabled={transfers.state.busy} onPress={()=>void decide('cancel')}/>}
 <Button secondary label="Actualizar solicitud y revisión" disabled={demo||transfers.state.busy} loading={transfers.state.loading} onPress={()=>{setPreviewAttempt(n=>n+1);void transfers.controller?.open(row.id);}}/>
 {row.effectiveState==='accepted'&&<Button label="Ir a mis anuncios" onPress={()=>router.push('/my-listings')}/>}
 </>}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},content:{width:'100%',maxWidth:880,alignSelf:'center',padding:20,gap:20,paddingBottom:42},card:{backgroundColor:colors.white,padding:20,borderRadius:24,gap:10},title:{fontSize:19,lineHeight:26,color:colors.ink,fontWeight:'600'},status:{color:colors.primary,fontSize:14,fontWeight:'600'},detail:{color:colors.muted,fontSize:14,lineHeight:22},photos:{gap:12},photo:{width:230,height:170,borderRadius:18},placeholder:{backgroundColor:colors.paper,padding:18,justifyContent:'center',alignItems:'center'}});
