import {useEffect,useState,type ReactNode} from 'react';
import {ActivityIndicator,KeyboardAvoidingView,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {createThemedStyles} from '../../theme';
import {Button,Icon,IconButton} from '../ui';
import {SelectionField,type SelectOption} from '../SelectionField';

export type AdminFilter={key:string;label:string;options?:readonly SelectOption[];kind?:'date'};
export const options=(values:Record<string,string>):SelectOption[]=>Object.entries(values).map(([value,label])=>({value,label}));
export const anyOption={value:'',label:'Todos'};
export function AdminToolbar({query,onSearch,filters,onFilters,fields,sort,onSort,allowName=true,disabled=false}: {
  query:string;onSearch(value:string):void;filters:Record<string,string>;onFilters(value:Record<string,string>):void;fields:AdminFilter[];sort:string;onSort(value:string):void;allowName?:boolean;disabled?:boolean;
}) {
  const {styles:s,colors}=useStyles();const [text,setText]=useState(query),[open,setOpen]=useState(false),[draft,setDraft]=useState(filters),[issue,setIssue]=useState('');
  useEffect(()=>setText(query),[query]);
  const applied=fields.filter(field=>!!filters[field.key]&&filters[field.key]!=='all');
  const submit=()=>{if(!disabled)onSearch(text.trim());};
  return <View style={s.toolbar}>
    <View style={s.search}><Icon name="search-outline" color={colors.muted} size={19}/><TextInput value={text} onChangeText={setText} onSubmitEditing={submit} maxLength={100} editable={!disabled} accessibilityLabel="Buscar resultados" placeholder="Buscar…" placeholderTextColor={colors.muted} style={s.input} returnKeyType="search" autoCorrect={false}/><Pressable disabled={disabled} accessibilityRole="button" accessibilityLabel="Buscar" onPress={submit} style={s.smallButton}><Icon name="arrow-forward" color={colors.primary} size={20}/></Pressable></View>
    <View style={s.row}>
      {!!fields.length&&<Pressable disabled={disabled} accessibilityRole="button" accessibilityLabel={`Filtros${applied.length?`, ${applied.length} activos`:''}`} onPress={()=>{setDraft(filters);setIssue('');setOpen(true);}} style={[s.control,applied.length>0&&s.active]}><Icon name="options-outline" color={colors.primary} size={18}/><Text style={s.controlText}>Filtros{applied.length?` · ${applied.length}`:''}</Text></Pressable>}
      <SelectionField label="Ordenar resultados" value={sort} options={options({...{newest:'Más recientes',oldest:'Más antiguos'},...(allowName?{name:'Nombre A–Z'}:{})})} onChange={onSort} disabled={disabled} renderTrigger={show=><Pressable disabled={disabled} accessibilityRole="button" accessibilityLabel="Ordenar resultados" onPress={show} style={s.control}><Icon name="swap-vertical-outline" color={colors.primary} size={18}/><Text style={s.controlText}>{sort==='name'?'Nombre A–Z':sort==='oldest'?'Más antiguos':'Más recientes'}</Text></Pressable>}/>
    </View>
    {!!applied.length&&<View style={s.row}>{applied.map(field=><Pressable key={field.key} disabled={disabled} accessibilityRole="button" accessibilityLabel={`Quitar filtro ${field.label}`} onPress={()=>onFilters({...filters,[field.key]:''})} style={s.chip}><Text style={s.chipText}>{field.options?.find(option=>option.value===filters[field.key])?.label??`${field.kind==='date'?`${field.label}: `:''}${filters[field.key]}`}</Text><Icon name="close" size={15} color={colors.primary}/></Pressable>)}</View>}
    <Modal transparent visible={open} animationType="fade" onRequestClose={()=>setOpen(false)}><KeyboardAvoidingView behavior="padding" style={s.overlay}><View accessibilityViewIsModal style={s.sheet}><View style={s.row}><Text accessibilityRole="header" style={s.sheetTitle}>Filtrar resultados</Text><IconButton name="close" label="Cerrar filtros" onPress={()=>setOpen(false)}/></View><ScrollView contentContainerStyle={s.fields} keyboardShouldPersistTaps="handled">{fields.map(field=>field.kind==='date'?<View key={field.key} style={{gap:8}}><Text style={s.cardTitle}>{field.label}</Text><TextInput accessibilityLabel={field.label} value={draft[field.key]??''} onChangeText={value=>setDraft(previous=>({...previous,[field.key]:value}))} placeholder="AAAA-MM-DD" placeholderTextColor={colors.muted} maxLength={10} autoCorrect={false} style={[s.search,{padding:14,minHeight:50,color:colors.ink}]}/></View>:<SelectionField key={field.key} label={field.label} value={draft[field.key]??''} options={[anyOption,...(field.options??[])]} onChange={value=>setDraft(previous=>({...previous,[field.key]:value}))}/>)}</ScrollView>{!!issue&&<Text accessibilityRole="alert" style={{color:colors.danger}}>{issue}</Text>}<View style={s.row}><View style={s.flex}><Button label="Limpiar" secondary onPress={()=>{setDraft({...filters,...Object.fromEntries(fields.map(field=>[field.key,'']))});setIssue('');}} /></View><View style={s.flex}><Button label="Aplicar" onPress={()=>{for(const field of fields.filter(field=>field.kind==='date')){const value=draft[field.key];if(value&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(`${value}T00:00:00Z`))||new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)!==value)){setIssue('Escribe una fecha válida con el formato AAAA-MM-DD.');return;}}if(draft.from&&draft.to&&draft.from>draft.to){setIssue('La fecha inicial debe ser anterior a la final.');return;}onFilters({...filters,...draft});setOpen(false);}}/></View></View></View></KeyboardAvoidingView></Modal>
  </View>;
}
export function AdminPagination({offset,total,hasMore,loading,previous,next}: {offset:number;total:number|null;hasMore:boolean;loading:boolean;previous():void;next():void}) {
  const {styles:s}=useStyles();
  return <View style={s.pagination}><Text accessibilityLiveRegion="polite" style={s.meta}>{total===null?'Consultando resultados…':total===0?'0 resultados':`${offset+1}–${Math.min(offset+20,total)} de ${total}`}</Text>{total!==null&&total>20&&<View style={s.row}><Pressable disabled={loading||offset===0} accessibilityRole="button" accessibilityLabel="Página anterior" onPress={previous} style={[s.pageButton,(loading||offset===0)&&s.disabled]}><Text style={s.controlText}>Anterior</Text></Pressable><Text style={s.meta}>{Math.floor(offset/20)+1} / {Math.ceil(total/20)}</Text><Pressable disabled={loading||!hasMore} accessibilityRole="button" accessibilityLabel="Página siguiente" onPress={next} style={[s.pageButton,(loading||!hasMore)&&s.disabled]}><Text style={s.controlText}>Siguiente</Text></Pressable></View>}{loading&&<ActivityIndicator/>}</View>;
}
export function AdminCard({title,subtitle,badge,children,onPress}: {title:string;subtitle?:string;badge?:ReactNode;children?:ReactNode;onPress?:()=>void}) {
  const {styles:s,colors}=useStyles();const copy=<><View style={s.cardHeader}><View style={s.flex}><Text accessibilityRole="header" style={s.cardTitle}>{title}</Text>{!!subtitle&&<Text style={s.meta}>{subtitle}</Text>}</View>{onPress&&<Icon name="chevron-forward" size={19} color={colors.muted}/>}</View>{badge}{children}</>;
  return onPress?<Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.card,pressed&&{opacity:.75}]}>{copy}</Pressable>:<View style={s.card}>{copy}</View>;
}
export function AdminStatus({label,tone='neutral'}:{label:string;tone?:'neutral'|'green'|'amber'|'danger'|'blue'}) {const {styles:s,colors}=useStyles();const background=tone==='green'?colors.softGreen:tone==='amber'?colors.softAmber:tone==='danger'?colors.softDanger:tone==='blue'?colors.softBlue:colors.paper;const color=tone==='green'?colors.green:tone==='amber'?colors.amber:tone==='danger'?colors.danger:tone==='blue'?colors.primary:colors.muted;return <View style={[s.status,{backgroundColor:background}]}><Text style={[s.statusText,{color}]}>{label}</Text></View>;}
const useStyles=createThemedStyles(colors=>StyleSheet.create({
  toolbar:{gap:10},search:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:16,flexDirection:'row',gap:10,alignItems:'center',paddingLeft:14},input:{flex:1,minWidth:0,minHeight:50,fontSize:16,color:colors.ink},smallButton:{width:48,minHeight:48,alignItems:'center',justifyContent:'center'},row:{flexDirection:'row',gap:10,alignItems:'center',flexWrap:'wrap'},flex:{flex:1,minWidth:0},control:{minHeight:44,borderWidth:1,borderColor:colors.border,borderRadius:13,backgroundColor:colors.surface,paddingHorizontal:13,flexDirection:'row',gap:7,alignItems:'center'},active:{borderColor:colors.primary,backgroundColor:colors.softBlue},controlText:{color:colors.primary,fontSize:13,fontWeight:'600'},chip:{flexDirection:'row',alignItems:'center',gap:7,borderRadius:16,paddingVertical:8,paddingHorizontal:11,backgroundColor:colors.softBlue},chipText:{color:colors.primary,fontSize:12},overlay:{flex:1,backgroundColor:colors.overlay,padding:18,justifyContent:'center'},sheet:{width:'100%',maxWidth:480,alignSelf:'center',maxHeight:'88%',backgroundColor:colors.surface,borderRadius:24,padding:20,gap:16},sheetTitle:{flex:1,color:colors.ink,fontSize:23,fontWeight:'700'},fields:{gap:18,paddingBottom:8},pagination:{gap:12,alignItems:'center',paddingVertical:14},meta:{color:colors.muted,fontSize:13,lineHeight:20},pageButton:{minHeight:44,paddingHorizontal:17,justifyContent:'center',borderRadius:13,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},disabled:{opacity:.35},card:{padding:18,gap:12,borderWidth:1,borderColor:colors.border,borderRadius:20,backgroundColor:colors.surface},cardHeader:{flexDirection:'row',alignItems:'center',gap:12},cardTitle:{color:colors.ink,fontSize:17,lineHeight:23,fontWeight:'600'},status:{alignSelf:'flex-start',borderRadius:8,paddingHorizontal:9,paddingVertical:5},statusText:{fontSize:12,fontWeight:'600'},
}));
