import {object,uuid,nullableUuid,integer,text,timestamp,invalidAgencyData} from '../deals/domain.ts';
import {followupError} from '../deals/domain.ts';
import type {SaleRequest,SaleClosure,RequestSale,DecideSale,SaleDecision} from './types.ts';
function money(v:unknown):number {if(typeof v!=='number'||!Number.isFinite(v)||v<=0||v>1e9||Math.abs(v*100-Math.round(v*100))>0.00001)throw invalidAgencyData();return v;}
function keys(v:unknown,allowed:string[]){if(Object.keys(object(v)).some(k=>!allowed.includes(k)))throw invalidAgencyData();}
export function validateRequest(v:RequestSale){keys(v,['winningDealId','executingManagerId','amountUsd','occurredAt','expectedPropertyVersion','expectedAuthorityVersion','clientRequestId']);uuid(v.winningDealId);uuid(v.executingManagerId);uuid(v.clientRequestId);money(v.amountUsd);timestamp(v.occurredAt);integer(v.expectedPropertyVersion,1);integer(v.expectedAuthorityVersion,1);return v;}
export function validateDecision(v:DecideSale){keys(v,['requestId','action','expectedRequestVersion','expectedPropertyVersion','expectedAuthorityVersion','note','clientRequestId']);uuid(v.requestId);uuid(v.clientRequestId);integer(v.expectedRequestVersion,1);integer(v.expectedPropertyVersion,1);integer(v.expectedAuthorityVersion,1);if(!['confirm','reject','cancel'].includes(v.action)||text(v.note).length>500)throw invalidAgencyData();return v;}
export function decodeClosure(value:unknown):SaleClosure{const v=object(value);return{id:uuid(v.id),propertyId:uuid(v.propertyId),cycleId:uuid(v.cycleId),requestId:nullableUuid(v.requestId),originAgencyId:nullableUuid(v.originAgencyId),executingAgencyId:nullableUuid(v.executingAgencyId),executingManagerId:nullableUuid(v.executingManagerId),confirmedBy:uuid(v.confirmedBy),confirmedAt:timestamp(v.confirmedAt),amountUsd:v.amountUsd===null?null:money(v.amountUsd)};}
export function decodeSaleRequest(value:unknown):SaleRequest{const v=object(value);if(!['pending','confirmed','rejected','cancelled'].includes(String(v.state))||typeof v.canDecide!=='boolean'||typeof v.canCancel!=='boolean')throw invalidAgencyData();return{id:uuid(v.id),propertyId:uuid(v.propertyId),cycleId:uuid(v.cycleId),originAgencyId:nullableUuid(v.originAgencyId),executingAgencyId:uuid(v.executingAgencyId),executingManagerId:uuid(v.executingManagerId),winningDealId:uuid(v.winningDealId),amountUsd:money(v.amountUsd),occurredAt:timestamp(v.occurredAt),state:v.state as SaleRequest['state'],version:integer(v.version,1),propertyTitle:text(v.propertyTitle),executingAgencyName:text(v.executingAgencyName),executingManagerName:text(v.executingManagerName),buyerLabel:text(v.buyerLabel),evidenceSummary:text(v.evidenceSummary),expectedPropertyVersion:integer(v.expectedPropertyVersion,1),expectedAuthorityVersion:integer(v.expectedAuthorityVersion,1),affectedVisits:integer(v.affectedVisits),affectedDeals:integer(v.affectedDeals),canDecide:v.canDecide,canCancel:v.canCancel,closure:v.closure===null?null:decodeClosure(v.closure)};}
export function decodeDecision(v:unknown,id:string):SaleDecision{const r=object(v),request=decodeSaleRequest(r.request),closure=r.closure===null?null:decodeClosure(r.closure);if(request.id!==id||closure&&(closure.requestId!==id||closure.propertyId!==request.propertyId||closure.cycleId!==request.cycleId))throw invalidAgencyData();return{request,closure};}
export function closureError(e:unknown){const m=e instanceof Error?e.message:String(object(e).message??'');if(/SALE_STALE|ASSIGNMENT_CHANGED|VERSION_CONFLICT/.test(m))return 'La vivienda, la autorización, el acuerdo o el gestor cambiaron. Actualiza y corrige la solicitud.';if(/ORIGIN_REQUIRED/.test(m))return 'Solo la autoridad actual del origen puede confirmar o rechazar esta venta.';if(/SALE_EXECUTOR/.test(m))return 'Selecciona expresamente al responsable vigente del expediente como gestor ejecutor.';if(/SALE_INVALID/.test(m))return 'Revisa el importe final, la fecha y los datos del cierre.';return followupError(e);}
