import type {AgencyRequestContext,Page} from '../types';
import type {MessagingRequestContext} from '../../messaging/types';
export interface SaleClosure {id:string;propertyId:string;cycleId:string;requestId:string|null;originAgencyId:string|null;executingAgencyId:string|null;executingManagerId:string|null;confirmedBy:string;confirmedAt:string;amountUsd:number|null}
export interface SaleRequest {id:string;propertyId:string;cycleId:string;originAgencyId:string|null;executingAgencyId:string;executingManagerId:string;winningDealId:string;amountUsd:number;occurredAt:string;state:'pending'|'confirmed'|'rejected'|'cancelled';version:number;propertyTitle:string;executingAgencyName:string;executingManagerName:string;buyerLabel:string;evidenceSummary:string;expectedPropertyVersion:number;expectedAuthorityVersion:number;affectedVisits:number;affectedDeals:number;canDecide:boolean;canCancel:boolean;closure:SaleClosure|null}
export interface RequestSale {winningDealId:string;executingManagerId:string;amountUsd:number;occurredAt:string;expectedPropertyVersion:number;expectedAuthorityVersion:number;clientRequestId:string}
export interface DecideSale {requestId:string;action:'confirm'|'reject'|'cancel';expectedRequestVersion:number;expectedPropertyVersion:number;expectedAuthorityVersion:number;note:string;clientRequestId:string}
export interface SaleDecision {request:SaleRequest;closure:SaleClosure|null}
export interface AgencyClosureRepository {prepare(dealId:string,context:AgencyRequestContext):Promise<SalePreparation>;request(input:RequestSale,context:AgencyRequestContext):Promise<SaleRequest>;list(input:{scope:'incoming'|'outgoing';offset:number},context:AgencyRequestContext):Promise<Page<SaleRequest>>;decide(input:DecideSale,context:AgencyRequestContext):Promise<SaleDecision>;personalList(offset:number,context:MessagingRequestContext):Promise<Page<SaleRequest>>;personalDecide(input:DecideSale,context:MessagingRequestContext):Promise<SaleDecision>}
export interface SalePreparation {dealId:string;propertyId:string;propertyTitle:string;expectedPropertyVersion:number;expectedAuthorityVersion:number;executingManagerId:string|null;executingManagerName:string|null}
